// Real assistant handlers with fictional scoped data and deferred read requests.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript');
const cache=new Map(),state=[],refs=[],effects=[],calls=[],opened=[],navigated=[],records=[];let cursor=0,refCursor=0;
const props={org:{id:'fictional:mola',name:'Fictional Mola',members:[{id:'a',name:'Alice Test',role:'Member'}],permissions:{isOwner:false}},entries:[{id:'c',orgId:'fictional:mola',title:'October deposit',purpose:'Shared capital',type:'contribution',date:'2026-10-10',status:'Verified'}],open:true,onOpenChange:value=>opened.push(value),onNavigate:view=>navigated.push(view),onRecord:(id,view)=>records.push({id,view})};
const text=n=>typeof n==='string'?n:Array.isArray(n)?n.map(text).join(''):n?.props?text(n.props.children):'';
function find(n,p){if(Array.isArray(n)){for(const child of n){const r=find(child,p);if(r)return r;}return null;}if(!n||typeof n!=='object')return null;return p(n)?n:find(n.props?.children,p);}
const tick=()=>new Promise(setImmediate);
const originalFetch=global.fetch;global.fetch=async(url,options)=>{assert.equal(url,'/api/workspace');return new Promise((resolve,reject)=>calls.push({options,body:JSON.parse(options.body),resolve,reject}));};
function load(file){if(cache.has(file))return cache.get(file).exports;const m={exports:{}};cache.set(file,m);const req=name=>{
 if(name==='react')return {useState:initial=>{const i=cursor++;if(!(i in state))state[i]=initial;return [state[i],value=>state[i]=typeof value==='function'?value(state[i]):value];},useRef:value=>{const i=refCursor++;return refs[i]||(refs[i]={current:value});},useEffect:fn=>effects.push(fn)};
 if(name==='react/jsx-runtime')return {jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};
 if(name.startsWith('@/lib/'))return load(name.slice(2)+'.ts');
 return new Proxy({},{get:(_,key)=>String(key)});
 };vm.runInThisContext('(function(require,module,exports){'+ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText+'\n})')(req,m,m.exports);return m.exports;}
const Component=load('app/ask-mola.tsx').default,render=()=>{cursor=0;refCursor=0;effects.length=0;return Component(props);};
let tree=render();const cleanup=effects[0]();const question=value=>{find(tree,n=>n.type==='textarea').props.onChange({target:{value}});tree=render();};const send=()=>find(tree,n=>n.type==='form').props.onSubmit({preventDefault(){}});
(async()=>{
 assert.equal(find(tree,n=>n.type==='Dialog').props.modal,false);assert(text(tree).includes('Private receipt images'));assert(text(tree).includes('not saved to Mola'));
 question('open savings');await send();assert.deepEqual(navigated,['goals']);assert.equal(calls.length,0,'Navigation never asks AI or writes records');tree=render();
 question('find October');await send();tree=render();assert(find(tree,n=>n.type==='input'&&n.props.type==='search'));find(tree,n=>n.type==='button'&&text(n).includes('October deposit')).props.onClick();assert.deepEqual(records,[{id:'c',view:'contributions'}]);assert.deepEqual(opened,[false]);
 find(tree,n=>n.type==='button'&&text(n).trim()==='Chat').props.onClick();tree=render();question('How much has the group contributed?');const composer=find(tree,n=>n.type==='textarea');composer.props.onKeyDown({key:'Enter',shiftKey:true,nativeEvent:{isComposing:false},preventDefault(){throw new Error('Shift+Enter keeps a newline');}});assert.equal(calls.length,0);const request=composer.props.onKeyDown({key:'Enter',shiftKey:false,nativeEvent:{isComposing:false},preventDefault(){}}),duplicate=send();assert.equal(calls.length,1);assert.equal(calls[0].body.orgId,props.org.id);assert.equal(calls[0].body.action,'askMola');assert.equal(calls[0].body.useAI,false);assert.equal(calls[0].body.entries,undefined);assert(!JSON.stringify(calls[0].body).includes('October deposit'));tree=render();assert.equal(find(tree,n=>n.type==='textarea').props.disabled,true,'A pending answer cannot erase a newly typed chat draft');find(tree,n=>n.type==='button'&&text(n).includes('Quick search')).props.onClick();tree=render();find(tree,n=>n.type==='input'&&n.props.type==='search').props.onChange({target:{value:'Alice'}});tree=render();
 calls[0].resolve(Response.json({answer:'Verified contributions: $100.00.',asOf:'2026-10-10T15:00:00Z',mode:'records',aiAvailable:true,sources:[{label:'Group statement',view:'statements'}]}));await Promise.all([request,duplicate]);await tick();tree=render();assert.equal(find(tree,n=>n.type==='input'&&n.props.type==='search').props.value,'Alice','A completed chat answer must not erase the quick-search query');find(tree,n=>n.type==='button'&&text(n).trim()==='Chat').props.onClick();tree=render();assert(text(tree).includes('Verified contributions: $100.00.'));assert.equal(find(tree,n=>n.type==='textarea').props.value,'');assert(find(tree,n=>n.type==='input'&&n.props.type==='checkbox'));
 props.open=false;tree=render();props.open=true;tree=render();assert(text(tree).includes('Verified contributions: $100.00.'),'Closing/reopening does not discard the session conversation');
 find(tree,n=>n.type==='button'&&text(n).includes('Group statement')).props.onClick();assert.equal(navigated.at(-1),'statements');
 props.disabled=true;tree=render();question('open contributions');await send();assert.equal(navigated.at(-1),'statements','An in-progress company save prevents assistant navigation');props.disabled=false;tree=render();
 question('Explain the company');const failed=send();calls[1].resolve(Response.json({error:'Fictional unavailable service'},{status:503}));await failed;await tick();tree=render();assert(text(tree).includes('Fictional unavailable service'));assert.equal(find(tree,n=>n.type==='textarea').props.value,'Explain the company','Failed asks retain the draft');
 const pending=send();assert.equal(calls.length,3);cleanup();assert.equal(calls[2].options.signal.aborted,true);calls[2].resolve(Response.json({answer:'Stale answer',asOf:'2026-10-10',sources:[]}));await pending;await tick();tree=render();assert(!text(tree).includes('Stale answer'),'Departed accounts cannot receive old responses');
 console.log('ASSISTANT UI PASS: nonmodal chat/search, exact navigation and record links, scoped read requests, duplicate guard, retained conversation/errors, save lock and abort on account/organization departure.');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{global.fetch=originalFetch;});
