// Exact recorded-dues behavior, using production review/standing helpers.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),cache=new Map();
function load(file){if(cache.has(file))return cache.get(file).exports;const mod={exports:{}};cache.set(file,mod);const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInThisContext('(function(require,module,exports){'+code+'\n})')(name=>load(path.join(path.dirname(file),name)+'.ts'),mod,mod.exports);return mod.exports;}
const {createReviewDraft,reviewRequest,reviewImpact,suggestedReviewCredit,reviewObligations}=load('lib/contribution-review.ts');
const org={id:'mola',members:[{id:'alice',name:'Fictional Alice'}]};
const due=(id,minor,currency='USD',extra={})=>({id,orgId:'mola',type:'obligation',memberId:'alice',currency,amountMinor:minor,title:id,date:'2026-11-01',...extra});
const payment=(extra={})=>({id:'payment',orgId:'mola',type:'contribution',memberId:'alice',currency:'USD',amountMinor:10000,title:'Fictional payment',status:'Verified',canReview:true,reviews:[{outcome:'Verified',creditMinor:4000,obligationId:'jan',evidence:'Earlier receipt',actor:'private-principal',at:'2026-10-04T01:00:00Z'}],submissionObligationId:'jan',...extra});
const jan=due('jan',10000),feb=due('feb',5000),p=payment(),entries=[jan,feb,p];
let draft=createReviewDraft(org,p,entries);assert.equal(draft.credit,'40.00');assert.equal(draft.obligationId,'jan');assert.equal(draft.outcome,'Verified');assert.equal(draft.reviewCount,1);
let impact=reviewImpact(draft);assert.deepEqual(impact.rows.map(r=>[r.id,r.beforeRemaining,r.afterRemaining]),[['jan',6000,6000]]);assert.equal(impact.unallocatedMinor,6000);
draft.evidence='Updated evidence reference';const request=reviewRequest(draft);assert.equal(request.credit,'40.00');assert.equal(request.obligationId,'jan');assert.equal(request.reviewSnapshot,undefined);assert(!JSON.stringify(request).includes('private-principal'));assert.deepEqual(Object.keys(request).sort(),['action','credit','entryId','evidence','obligationId','orgId','outcome','reviewCount'].sort());
impact=reviewImpact({...draft,obligationId:'feb',credit:'50.00'});assert.deepEqual(impact.rows.map(r=>[r.id,r.beforeRemaining,r.afterRemaining]),[['jan',6000,10000],['feb',5000,0]]);assert.equal(impact.unallocatedMinor,5000);
impact=reviewImpact({...draft,obligationId:'',credit:''});assert.equal(impact.rows[0].afterRemaining,10000);assert.equal(impact.unallocatedMinor,10000);
impact=reviewImpact({...draft,outcome:'Rejected'});assert.equal(impact.rows[0].afterRemaining,10000);assert.equal(impact.unallocatedMinor,undefined);assert.equal(reviewRequest({...draft,outcome:'Rejected'}).credit,'0.00');assert.equal(reviewRequest({...draft,outcome:'Rejected'}).obligationId,'');
assert.equal(suggestedReviewCredit(draft,'jan'),'40.00','Returning to the saved assignment restores its saved partial amount');assert.equal(suggestedReviewCredit(draft,'feb'),'50.00');
assert.match(reviewImpact({...draft,credit:'100.01'}).error,/exceed/);assert.throws(()=>reviewRequest({...draft,credit:'100.01'}),/exceed/);assert.match(reviewImpact({...draft,credit:'0'}).error,/positive/);assert.match(reviewImpact({...draft,credit:'40.001'}).error,/positive/);assert.match(reviewImpact({...draft,obligationId:'foreign'}).error,/same currency/);assert.throws(()=>reviewRequest({...draft,evidence:'no'}),/five/);

// First review suggests only the outstanding amount; extras do not cover future dues.
const fresh=payment({status:'Awaiting verification',reviews:[],amountMinor:15000});draft=createReviewDraft(org,fresh,[jan,feb,fresh]);assert.equal(draft.obligationId,'jan');assert.equal(draft.credit,'100.00');assert.equal(reviewImpact(draft).unallocatedMinor,5000);assert.equal(reviewImpact(draft).rows.length,1);
const paid=payment({id:'other-payment',amountMinor:10000,reviews:[{outcome:'Verified',creditMinor:10000,obligationId:'jan'}]});draft=createReviewDraft(org,fresh,[jan,feb,paid,fresh]);assert.equal(draft.obligationId,'');assert.equal(draft.credit,'');assert.equal(reviewImpact(draft).unallocatedMinor,15000);assert.equal(suggestedReviewCredit(draft,'jan'),'','A covered obligation needs an explicit amount to assign excess');
const partial=payment({...paid,amountMinor:6000,reviews:[{outcome:'Verified',creditMinor:6000,obligationId:'jan'}]});draft=createReviewDraft(org,fresh,[jan,feb,partial,fresh]);assert.equal(draft.credit,'40.00');
impact=reviewImpact({...draft,credit:'150.00'});assert.equal(impact.rows[0].afterExcess,11000);assert.equal(impact.rows[0].afterRemaining,0);assert.equal(impact.unallocatedMinor,0);
const unallocated=payment({submissionObligationId:'jan',reviews:[{outcome:'Verified',creditMinor:0,obligationId:''}]});draft=createReviewDraft(org,unallocated,[jan,unallocated]);assert.equal(draft.obligationId,'','A correction cannot infer a new assignment from the submission deadline');assert.equal(reviewImpact(draft).unallocatedMinor,10000);
const rejected=payment({status:'Rejected',reviews:[{outcome:'Rejected',creditMinor:0,obligationId:''}]});draft=createReviewDraft(org,rejected,[jan,rejected]);assert.equal(draft.outcome,'Rejected');assert.equal(draft.obligationId,'');
const provisional=payment({status:'Owner reconciled',canReview:false,canOwnerReconcile:true,reviews:[{outcome:'Owner reconciled',creditMinor:4000,obligationId:'jan'}]});draft=createReviewDraft(org,provisional,[jan,provisional]);assert.equal(draft.outcome,'Owner reconciled');assert.equal(draft.credit,'40.00');assert.throws(()=>reviewRequest({...draft,evidence:'Fictional receipt',outcome:'Verified'}),/allowed/);

const xaf=payment({currency:'XAF',amountMinor:1000,reviews:[{outcome:'Verified',creditMinor:400,obligationId:'xaf'}],submissionObligationId:'xaf'});draft=createReviewDraft(org,xaf,[due('xaf',1000,'XAF'),xaf]);assert.equal(draft.credit,'400');assert.equal(reviewImpact(draft).unallocatedMinor,600);assert.match(reviewImpact({...draft,credit:'400.50'}).error,/whole/);
const isolated=createReviewDraft(org,p,[jan,due('foreign',999999,'USD',{orgId:'other'}),due('member-b',999999,'USD',{memberId:'bob'}),due('cad',999999,'CAD'),p]);assert.equal(reviewObligations(isolated).length,1);assert.equal(suggestedReviewCredit(isolated,'foreign'),'');
const malformed=payment({reviews:[{outcome:'Verified',creditMinor:11000,obligationId:'jan'}]});draft=createReviewDraft(org,malformed,[jan,malformed]);assert.equal(draft.obligationId,'');assert.match(reviewImpact(draft).warning,/inconsistent/);assert.equal(reviewImpact(draft).rows[0].beforeRemaining,10000);
const snapshot=createReviewDraft(org,p,entries);p.reviews[0].creditMinor=9000;jan.amountMinor=90000;org.members[0].name='Changed elsewhere';assert.equal(snapshot.credit,'40.00');assert.equal(snapshot.reviewSnapshot.memberName,'Fictional Alice');assert.equal(reviewImpact(snapshot).rows[0].afterRemaining,6000,'Later source changes cannot rewrite the reviewed snapshot');
assert.throws(()=>createReviewDraft(org,payment({canReview:false,canOwnerReconcile:false}),entries),/authorized/);
console.log('CONTRIBUTION REVIEW PASS: preserved partial/unallocated/rejected/provisional state, replacement/release/excess previews, safe first-credit suggestions, exact XAF amounts, scope isolation, malformed-credit warnings, frozen snapshots and minimal validated requests.');
