// Actual route handlers with isolated SQLite and a controlled server clock.
// No production records, fees, email, or transfers.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ts=require('typescript'),{DatabaseSync}=require('node:sqlite'),root=path.resolve(__dirname,'..'),sql=new DatabaseSync(':memory:');
for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
let identity,clock='2026-10-01T15:59:59.000Z',beforeInsert;
const RealDate=Date;class Clock extends RealDate{constructor(...args){super(...(args.length?args:[clock]));}static now(){return RealDate.parse(clock);}}
const db={prepare(query){let values=[];const statement={bind(...v){values=v;return statement;},async first(){return sql.prepare(query).get(...values)||null;},async all(){return {results:sql.prepare(query).all(...values)};},async run(){if(beforeInsert&&query.startsWith('INSERT OR IGNORE INTO entries')){const hook=beforeInsert;beforeInsert=undefined;hook();}return {meta:{changes:Number(sql.prepare(query).run(...values).changes)}};}};return statement;},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const req=name=>{if(name==='cloudflare:workers')return {env:{MOLA_OWNER_EMAIL:'owner@example.test'}};if(name==='@/lib/cloudflare-auth')return {cloudflareUser:async()=>identity?{...identity,emailVerified:true}:null};if(name==='@/lib/database')return {database:()=>db};if(name.startsWith('@/'))return load(path.join(root,name.slice(2)+'.ts'));if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name+'.ts'));return require(name);};vm.runInThisContext('(function(require,module,exports,Date){'+source+'\n})',{filename:file})(req,module,module.exports,Clock);return module.exports;}
const {GET,POST}=load(path.join(root,'app/api/workspace/route.ts')),{captureDeadline,submissionTiming,obligationPastDue,formatTimestamp}=load(path.join(root,'lib/deadlines.ts')),{memberStatement,statementCsv}=load(path.join(root,'lib/statements.ts')),{activityFor}=load(path.join(root,'lib/activity.ts'));
let org;const login=who=>{identity=who?{userId:who,email:who+'@example.test',displayName:who}:null;};
async function get(who){login(who);const response=await GET(),data=await response.json();assert.equal(response.status,200,JSON.stringify(data));return data;}
async function owner(){org=(await get('owner')).organizations.find(o=>o.mode==='Shared ownership');return org;}
async function post(who,body,status=200){login(who);const response=await POST(new Request('https://test.example/api/workspace',{method:'POST',headers:{origin:'https://test.example','content-type':'application/json'},body:JSON.stringify({orgId:org.id,...body})})),data=await response.json();assert.equal(response.status,status,JSON.stringify(data));return data;}
const draft=(action,extra={})=>({action,submissionId:crypto.randomUUID(),title:'Fictional '+action,memberId:'founder-2',amount:'100.00',currency:'USD',method:'Bank transfer (external)',date:'2026-10-01',reference:'TEST',purpose:'Fictional deadline acceptance',...extra});
const edit=(due,extra={})=>({action:'obligationDeadline',version:org.version,entryId:due.id,deadlineAt:due.deadline?.at||'',historyCount:due.deadlineHistory?.length||0,deadlineTime:'11:00',deadlineTimeZone:'America/Detroit',reason:'Approved member cutoff correction',...extra});
(async()=>{
 assert.equal(captureDeadline('2026-10-01','12:00','America/Detroit').at,'2026-10-01T16:00:00.000Z');assert.equal(captureDeadline('2026-01-05','12:00','America/Detroit').at,'2026-01-05T17:00:00.000Z');assert.equal(captureDeadline('2026-10-01','12:00','Asia/Kathmandu').at,'2026-10-01T06:15:00.000Z');assert.throws(()=>captureDeadline('2026-03-08','02:30','America/Detroit'),/does not exist/);assert.throws(()=>captureDeadline('2026-11-01','01:30','America/Detroit'),/repeats/);assert.throws(()=>captureDeadline('2026-02-30','12:00','UTC'));assert.throws(()=>captureDeadline('2026-10-01','25:00','UTC'));assert.throws(()=>captureDeadline('2026-10-01','12:00','Invalid/Zone'));assert(formatTimestamp(clock,'America/Detroit').includes('America/Detroit'));console.log('PASS: summer, winter, fractional offsets, explicit time zones, and daylight-saving gap/overlap rejection');
 await owner();for(const [index,name] of [[1,'owner'],[2,'alice'],[3,'bob']]){await post('owner',{action:'memberAccess',version:org.version,memberId:'founder-'+index,name,email:name+'@example.test',enabled:true,canReview:true,role:'Member'});await owner();}await get('alice');await get('bob');await owner();
 await post('owner',draft('obligation'),400);await post('alice',draft('obligation',{deadlineTime:'12:00',deadlineTimeZone:'America/Detroit'}),403);
 let due=(await post('owner',draft('obligation',{deadlineTime:'12:00',deadlineTimeZone:'America/Detroit',created:'1900-01-01T00:00:00Z'}))).entry;assert.equal(due.created,clock);assert(!obligationPastDue(due,due.deadline.at));assert(obligationPastDue(due,'2026-10-01T16:00:00.001Z'));
 const body=draft('contribution',{submissionObligationId:due.id,date:'2026-09-01',created:'1900-01-01T00:00:00Z',submissionDeadline:{at:'2099-01-01T00:00:00Z'}});
 clock=due.deadline.at;let payment=(await post('alice',body)).entry;assert.equal(payment.created,clock);assert.equal(submissionTiming(payment),'On-time submission');assert.equal(payment.submissionDeadline.at,due.deadline.at);clock='2026-10-01T16:00:00.001Z';const late=(await post('alice',draft('contribution',{submissionObligationId:due.id}))).entry;assert.equal(submissionTiming(late),'Late submission');assert.equal((await post('alice',body)).entry.created,payment.created);
 console.log('PASS: server-owned timestamps, backdated payment dates, inclusive cutoff boundary, late submission, and idempotent retry');
 await post('alice',edit(due),403);await post('owner',edit(due,{version:org.version-1}),409);const stale=edit(due);due=(await post('owner',stale)).entry;assert.equal(due.deadlineHistory.length,1);assert.equal(due.deadlineHistory[0].actor,'');await post('owner',stale,409);assert.equal((await post('alice',body)).entry.submissionDeadline.at,'2026-10-01T16:00:00.000Z');
 payment=(await post('bob',{action:'review',entryId:payment.id,reviewCount:0,outcome:'Verified',evidence:'Fictional receipt checked independently',obligationId:due.id,credit:'100.00'})).entry;assert.equal(payment.created,'2026-10-01T16:00:00.000Z');assert.equal(submissionTiming(payment),'On-time submission');assert.equal(payment.reviews[0].at,clock);assert.equal(payment.reviews[0].actor,'');
 const data=await get('alice'),loadedDue=data.entries.find(e=>e.id===due.id),before=memberStatement(org,data.entries,'founder-2','','','2026-10-01T14:59:59.999Z'),after=memberStatement(org,data.entries.filter(e=>e.id!==payment.id),'founder-2','','','2026-10-01T15:00:00.001Z');assert.equal(before.summaries[0].overdue,0);assert.equal(after.summaries[0].overdue,10000);const csv=statementCsv(org,after);assert(csv.includes('Recorded at (UTC)'));assert(csv.includes('America/Detroit'));assert(csv.includes('Late submission'));assert(!activityFor(org,data.entries,'2026-10-01T16:00:01Z').some(e=>e.entryId===loadedDue.id&&e.kind==='overdue'));
 console.log('PASS: owner-only versioned deadline history, immutable captured cutoffs across edits/reviews, exact overdue time, and statement export');
 await post('alice',draft('contribution',{memberId:'founder-3',submissionObligationId:due.id}),403);await post('alice',draft('contribution',{currency:'CAD',submissionObligationId:due.id}),400);await post('alice',draft('contribution',{submissionObligationId:late.id}),400);
 const legacy={...due,id:org.id+':legacy',deadline:undefined,deadlineHistory:undefined};sql.prepare('INSERT INTO entries VALUES (?,?,?,?)').run(legacy.id,org.id,JSON.stringify(legacy),legacy.created);const legacyPayment=(await post('alice',draft('contribution',{submissionObligationId:legacy.id}))).entry;assert.equal(submissionTiming(legacyPayment),'Cutoff time not captured');assert(obligationPastDue(legacy,'2026-10-02T00:00:00Z'));assert(!obligationPastDue(legacy,'2026-10-01T23:59:59Z'));assert.equal(submissionTiming((await post('alice',draft('contribution'))).entry),'No obligation selected');
 beforeInsert=()=>{const raw=sql.prepare('SELECT data FROM entries WHERE id=?').get(due.id).data,next={...JSON.parse(raw),deadline:captureDeadline('2026-10-01','13:00','America/Detroit')};sql.prepare('UPDATE entries SET data=? WHERE id=?').run(JSON.stringify(next),due.id);};const race=draft('contribution',{submissionObligationId:due.id});await post('alice',race,409);assert.equal(sql.prepare('SELECT count(*) n FROM entries WHERE id=?').get(org.id+':'+race.submissionId).n,0);
 console.log('PASS: member/currency isolation, honest legacy missing-cutoff labels, and rejection of a cutoff changed during submission');
 await post('owner',{action:'scheduleSetup',version:org.version,effectiveDate:'2026-10-02',amount:'100.00'},400);await post('owner',{action:'scheduleSetup',version:org.version,effectiveDate:'2026-10-02',amount:'100.00',deadlineTime:'12:00',deadlineTimeZone:'America/Detroit'});await owner();const preview=(await post('owner',{action:'schedulePreview',version:org.version,from:'2026-10-02',weeks:1})).preview;assert(preview.records.every(e=>e.deadline.at==='2026-10-02T16:00:00.000Z'));await post('alice',{action:'scheduleDeadline',version:org.version,deadlineTime:'17:00',deadlineTimeZone:'UTC',reason:'Future cycles have a new cutoff'},403);await post('owner',{action:'scheduleDeadline',version:org.version,deadlineTime:'17:00',deadlineTimeZone:'UTC',reason:'Future cycles have a new cutoff'});await owner();await post('owner',{action:'scheduleGenerate',version:preview.version,from:'2026-10-02',weeks:1,token:preview.token},409);const fresh=(await post('owner',{action:'schedulePreview',version:org.version,from:'2026-10-02',weeks:1})).preview;assert.equal(fresh.records[0].deadline.at,'2026-10-02T17:00:00.000Z');await post('owner',{action:'scheduleGenerate',version:fresh.version,from:'2026-10-02',weeks:1,token:fresh.token});await owner();await post('owner',{action:'scheduleDeadline',version:org.version,deadlineTime:'18:00',deadlineTimeZone:'UTC',reason:'Only future generated cycles should change'});await owner();const generated=(await get('alice')).entries.filter(e=>e.method==='Scheduled obligation');assert.equal(generated.length,8);assert(generated.every(e=>e.deadline.at==='2026-10-02T17:00:00.000Z'));assert(generated.every(e=>e.created===clock));
 console.log('PASS: required weekly cutoffs, stale preview rejection, per-member cutoff snapshots, and unchanged previously generated dues');
 console.log('DEADLINE API PASS: 5 scenarios; no fees applied. Browser and real-member acceptance remain pending.');
})().catch(e=>{console.error(e);process.exitCode=1;});
