// Owner-export authorization plus preservation/integrity of a fictional migration.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ts=require('typescript'),{DatabaseSync}=require('node:sqlite'),root=path.resolve(__dirname,'..'),sql=new DatabaseSync(':memory:');
for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
let identity;const runtimeEnv={MOLA_OWNER_EMAIL:'owner@example.test'};const db={prepare(query){let values=[];const s={bind(...v){values=v;return s;},async first(){return sql.prepare(query).get(...values)||null;},async all(){return {results:sql.prepare(query).all(...values)};},async run(){return query.startsWith('SELECT')?{results:sql.prepare(query).all(...values),meta:{changes:0}}:{meta:{changes:Number(sql.prepare(query).run(...values).changes)}};}};return s;},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const cache=new Map();function load(file){file=path.resolve(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(cache.has(file))return cache.get(file).exports;const m={exports:{}};cache.set(file,m);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const req=name=>name==='cloudflare:workers'?{env:runtimeEnv}:name==='@/lib/cloudflare-auth'?{cloudflareUser:async()=>identity?{...identity,emailVerified:true}:null}:name==='@/lib/database'?{database:()=>db}:name.startsWith('@/')?load(path.join(root,name.slice(2)+(name.endsWith('.json')?'':'.ts'))):name.startsWith('.')?load(path.resolve(path.dirname(file),name+'.ts')):require(name);vm.runInThisContext('(function(require,module,exports){'+code+'\n})',{filename:file})(req,m,m.exports);return m.exports;}
const workspace=load(path.join(root,'app/api/workspace/route.ts')),exportRoute=load(path.join(root,'app/api/workspace/export/route.ts')),{ledgerExport}=load(path.join(root,'lib/ledger-export.ts'));
(async()=>{
 assert.equal((await exportRoute.GET()).status,401);identity={userId:'owner',email:'owner@example.test',displayName:'Owner'};assert.equal((await exportRoute.GET()).status,403);assert.equal((await workspace.GET()).status,200);const org=sql.prepare("SELECT id FROM organizations WHERE json_extract(data,'$.mode')='Shared ownership'").get().id;
 const created='2026-10-01T16:00:00.000Z',entry={id:'fictional-payment',orgId:org,type:'contribution',memberId:'founder-1',amountMinor:2500,currency:'USD',created,title:"Fictional O'Brien",submittedBy:'private-owner-id',reviews:[{actor:'private-reviewer-id',at:created,evidence:'Fictional receipt'}]};sql.prepare('INSERT INTO entries VALUES (?,?,?,?)').run(entry.id,org,JSON.stringify(entry),created);sql.prepare('INSERT INTO notification_reads VALUES (?,?,?,?,?)').run('private-read','private-reviewer-id',org,'fictional-payment:submitted',created);
 identity={userId:'member',email:'member@example.test',displayName:'Member'};assert.equal((await exportRoute.GET()).status,403);identity={userId:'owner',email:'owner@example.test',displayName:'Owner'};const response=await exportRoute.GET();assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');assert(response.headers.get('Content-Disposition').includes('attachment'));const snapshot=await response.json();assert.equal(snapshot.tables.entries[0].data,JSON.stringify(entry));assert.equal(snapshot.tables.notification_reads[0].user_id,'private-reviewer-id');assert.equal(snapshot.counts.entries,1);
 runtimeEnv.MOLA_MIGRATION_EXPORT_TOKEN='a'.repeat(64);identity=null;assert.equal((await exportRoute.GET()).status,401);assert.equal((await exportRoute.GET(new Request('https://test.example/api/workspace/export',{headers:{'X-Mola-Migration-Export-Token':'wrong'}}))).status,401);const serviceRequest=new Request('https://test.example/api/workspace/export',{headers:{'X-Mola-Migration-Export-Token':runtimeEnv.MOLA_MIGRATION_EXPORT_TOKEN}});assert.equal((await exportRoute.GET(serviceRequest)).status,200);identity={userId:'member',email:'member@example.test',displayName:'Member'};assert.equal((await exportRoute.GET(serviceRequest)).status,403);delete runtimeEnv.MOLA_MIGRATION_EXPORT_TOKEN;identity=null;assert.equal((await exportRoute.GET(serviceRequest)).status,401);identity={userId:'owner',email:'owner@example.test',displayName:'Owner'};const {validateExport,prepareImport}=await import('../scripts/prepare-supabase-import.mjs');const report=validateExport(snapshot),prepared=prepareImport(snapshot);assert.equal(report.reportedContributionMinorByCurrency.USD,2500);assert(prepared.sql.includes("O''Brien"));assert(prepared.sql.includes('private-owner-id'));assert(prepared.sql.includes('private-reviewer-id'));assert(prepared.sql.startsWith('-- Private ledger import'));assert(prepared.sql.includes('Target ledger is not empty; import stopped'));assert(prepared.sql.endsWith('COMMIT;\n'));assert(!prepared.sql.includes('INSERT INTO mola_private.auth_identity_links'));
 const tampered=structuredClone(snapshot);tampered.tables.entries[0].created='1900-01-01T00:00:00Z';assert.throws(()=>validateExport(tampered),/integrity/);assert.throws(()=>validateExport({model_projection:{truncated:true}}),/complete owner export/);const mismatched=structuredClone(snapshot);mismatched.counts.entries=2;assert.throws(()=>validateExport(mismatched),/count mismatch/);
 const corrupt=structuredClone(snapshot.tables);corrupt.entries[0].data=JSON.stringify({...entry,orgId:'another-org'});const bad=await ledgerExport(snapshot.projectId,corrupt,snapshot.exportedAt);assert.throws(()=>validateExport(bad),/organization mismatch/);const duplicate=structuredClone(snapshot.tables);duplicate.entries.push({...duplicate.entries[0]});const dup=await ledgerExport(snapshot.projectId,duplicate,snapshot.exportedAt);assert.throws(()=>validateExport(dup),/Duplicate/);
 console.log('PASS: owner-only complete export, private history/read state, exact JSON and recording time, digest and count validation, quoted SQL, and no automatic identity linking');
 const otherTables=structuredClone(snapshot.tables);otherTables.organizations[0].owner='other-owner';sql.prepare('UPDATE organizations SET owner=? WHERE id=?').run('other-owner',otherTables.organizations[0].id);assert.equal((await exportRoute.GET()).status,403);
 console.log('PASS: mixed-owner export rejected; no live migration or production data used');
})().catch(e=>{console.error(e);process.exitCode=1;});
