const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const cache=new Map();function load(file){if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const req=name=>load(path.join(path.dirname(file),name+'.ts'));vm.runInThisContext('(function(require,module,exports){'+code+'\n})')(req,module,module.exports);return module.exports;}
const {memberReadiness,pilotSetupRows,designatedRuleRecorded}=load('lib/pilot-setup.ts'),{acceptanceConsent}=load('lib/agreements.ts');
const org={id:'fictional',members:Array.from({length:8},(_,i)=>({id:'founder-'+i,name:'Founder '+i,role:'Member'})),agreement:'',accountLabel:'',accountHolder:'',version:1,permissions:{isOwner:true,memberId:''},approvalPolicy:{requiredApprovals:3}};
assert.equal(designatedRuleRecorded(org),false,'Legacy officer default is not a designated rule');assert(pilotSetupRows(org,[]).every(r=>!r.recorded));
org.members[0].access={enabled:true,claimed:true,canReview:true};assert.equal(memberReadiness(org).independentReviewConfigured,false,'One reviewer cannot independently review their own payments');
org.members[1].access={enabled:true,claimed:true,canReview:false};assert.equal(memberReadiness(org).independentReviewConfigured,true);
org.members[0].access.enabled=false;assert.equal(memberReadiness(org).reviewers,0);assert.equal(memberReadiness(org).independentReviewConfigured,false);org.members[0].access.enabled=true;
org.approvalPolicy={requiredApprovals:2,approverMemberIds:['founder-0','founder-1']};assert.equal(designatedRuleRecorded(org),true);assert.equal(pilotSetupRows(org,[]).find(r=>r.id==='funding').recorded,true);
org.approvalPolicy.approverMemberIds=['founder-0','founder-0'];assert.equal(designatedRuleRecorded(org),false);org.approvalPolicy.approverMemberIds=['founder-0','outsider'];assert.equal(designatedRuleRecorded(org),false);
org.weeklySchedule={startDate:'2026-10-05',rates:[{effectiveDate:'2026-10-05',amountMinor:10000}],deadlineRule:{time:'17:00',timeZone:'America/Detroit'}};assert.equal(pilotSetupRows(org,[]).find(r=>r.id==='schedule').recorded,true);delete org.weeklySchedule.deadlineRule;assert.equal(pilotSetupRows(org,[]).find(r=>r.id==='schedule').recorded,false);
org.accountLabel='Fictional treasury';assert.equal(pilotSetupRows(org,[]).find(r=>r.id==='account').recorded,false);org.accountHolder='Fictional Mola';assert.equal(pilotSetupRows(org,[]).find(r=>r.id==='account').recorded,true);
org.agreement='A saved working draft is not a published or accepted version.';assert.equal(pilotSetupRows(org,[]).find(r=>r.id==='agreement').recorded,false);
org.activeAgreementId='version-one';const entry={id:'version-one',orgId:org.id,type:'agreement',agreement:{revision:1,digest:'a'.repeat(64),acceptances:org.members.map(m=>({memberId:m.id,digest:'a'.repeat(64),consent:acceptanceConsent}))}};
assert.equal(pilotSetupRows(org,[entry]).find(r=>r.id==='agreement').recorded,true);entry.agreement.acceptances[7].memberId='outsider';assert.equal(pilotSetupRows(org,[entry]).find(r=>r.id==='agreement').recorded,false);
org.activeAgreementId='version-two';assert.equal(pilotSetupRows(org,[entry]).find(r=>r.id==='agreement').recorded,false,'Earlier acceptances cannot satisfy a replacement version');
console.log('PILOT SETUP PASS: current member/reviewer access, explicit distinct approvers, schedule/cutoff, account labels and exact-version founder acceptances drive setup status; no readiness is inferred from draft text or legacy defaults.');
