// Owner-private acceptance regression. No network or production data access.
// Run: node tests/pilot.cjs
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ts=require('typescript'),{DatabaseSync}=require('node:sqlite');
const root=path.resolve(__dirname,'..'),sql=new DatabaseSync(':memory:');
for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
let identity;
const db={prepare(query){let values=[];const statement={bind(...v){values=v;return statement;},async first(){return sql.prepare(query).get(...values)||null;},async all(){return {results:sql.prepare(query).all(...values)};},async run(){return {meta:{changes:Number(sql.prepare(query).run(...values).changes)}};}};return statement;},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const req=name=>{if(name==='cloudflare:workers')return {env:{MOLA_OWNER_EMAIL:'owner@example.test'}};if(name==='@/lib/cloudflare-auth')return {cloudflareUser:async()=>identity?{...identity,emailVerified:true}:null};if(name==='@/lib/database')return {database:()=>db};if(name.startsWith('@/'))return load(path.join(root,name.slice(2)+'.ts'));if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name+'.ts'));return require(name);};vm.runInThisContext('(function(require,module,exports){'+source+'\n})',{filename:file})(req,module,module.exports);return module.exports;}
const {GET,POST}=load(path.join(root,'app/api/workspace/route.ts'));
const {obligationStanding}=load(path.join(root,'lib/model.ts'));
let org,passed=0;
const login=who=>{identity=who?{userId:who,email:who+'@example.test',displayName:who}:null;};
async function get(who,status=200){login(who);const response=await GET();const data=await response.json();assert.equal(response.status,status,JSON.stringify(data));return data;}
async function post(who,body,status=200,origin='https://test.example'){login(who);const response=await POST(new Request('https://test.example/api/workspace',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({orgId:org.id,...body})}));const data=await response.json();assert.equal(response.status,status,JSON.stringify(data));if(response.ok&&body.action==='contribution'&&data.entry?.status==='Screenshot required'){const row=sql.prepare('SELECT data FROM entries WHERE id=?').get(data.entry.id),entry=JSON.parse(row.data);entry.status='Awaiting verification';entry.receipt={key:'fictional/'+entry.id,mime:'image/png',size:32,uploadedBy:who,uploadedAt:entry.created};sql.prepare('UPDATE entries SET data=? WHERE id=?').run(JSON.stringify(entry),entry.id);data.entry={...data.entry,status:'Awaiting verification',hasReceipt:true,canViewReceipt:true,canUploadReceipt:false};}return data;}
async function ownerOrg(){const data=await get('owner');org=data.organizations.find(o=>o.mode==='Shared ownership');return org;}
const done=label=>{passed++;console.log('PASS '+passed+': '+label);};
async function configure(name,index,role='Member',canReview=true,enabled=true){await ownerOrg();return post('owner',{action:'memberAccess',version:org.version,memberId:'founder-'+index,name,email:name+'@example.test',enabled,canReview,role});}
const draft=(action,memberId,amount='60.00',currency='USD')=>({action,submissionId:crypto.randomUUID(),title:'Fictional pilot '+action,memberId,amount,currency,date:'2026-01-05',method:'Bank transfer (external)',reference:'PILOT-PRIVATE-REFERENCE',purpose:'Fictional record; no money moved'});
const review=(payment,due,credit,outcome='Verified',reviewCount=payment.reviews?.length||0)=>({action:'review',entryId:payment.id,reviewCount,outcome,evidence:'PRIVATE-EVIDENCE-REFERENCE',obligationId:due?.id||'',credit});
(async()=>{
 await get(null,401);await ownerOrg();assert.equal((await get('owner')).organizations.length,1);await get('outsider',403);assert.equal(sql.prepare('SELECT count(*) n FROM organizations').get().n,1);
 await configure('owner',1,'President');await configure('alice',2);await configure('bob',3,'Treasurer');await configure('carol',4,'Secretary');
 const alice=await get('alice');await get('bob');await get('carol');assert.equal(alice.organizations.length,1);assert.equal(alice.organizations[0].permissions.memberId,'founder-2');assert.equal(alice.organizations[0].members.find(m=>m.id==='founder-3').access.email,'');assert.equal(alice.organizations[0].members.find(m=>m.id==='founder-2').access.userId,undefined);
 await post('alice',{...draft('note','founder-2'),orgId:'removed-land-group'},403);await post('owner',draft('note','founder-1'),403,'https://other.example');done('Sign-in linking, private member details, organization isolation and origin rejection');
 await ownerOrg();await post('alice',{action:'weeklyMinimum',version:org.version,amount:'250'},403);
 await post('owner',{action:'scheduleSetup',version:org.version,effectiveDate:'2026-01-05',amount:'100.00',deadlineTime:'17:00',deadlineTimeZone:'UTC'});await ownerOrg();await post('owner',{action:'scheduleRate',version:org.version,effectiveDate:'2026-01-12',amount:'250.00'});await ownerOrg();
 const p=(await post('owner',{action:'schedulePreview',version:org.version,from:'2026-01-05',weeks:2})).preview;assert.equal(p.records.length,16);assert.equal(p.totalMinor,280000);
 const generate={action:'scheduleGenerate',version:p.version,from:'2026-01-05',weeks:2,token:p.token};assert.equal((await post('owner',generate)).generated,16);await post('owner',generate,409);await ownerOrg();const retry=(await post('owner',{action:'schedulePreview',version:org.version,from:'2026-01-05',weeks:2})).preview;assert.equal(retry.records.length,0);assert.equal(retry.skipped,16);
 await post('owner',{action:'scheduleGenerate',version:retry.version,from:'2026-01-05',weeks:2,token:retry.token});await post('owner',{action:'scheduleRate',version:org.version,effectiveDate:'2026-01-12',amount:'500'},409);
 let data=await get('alice');const due=data.entries.find(e=>e.type==='obligation'&&e.memberId==='founder-2'&&e.date==='2026-01-05'),future=data.entries.find(e=>e.type==='obligation'&&e.memberId==='founder-2'&&e.date==='2026-01-12');assert.equal(due.amountMinor,10000);assert.equal(future.amountMinor,25000);done('Two weekly cycles, future minimum change, immutable historical dues and duplicate generation');
 const body=draft('contribution','founder-2');let payment=(await post('alice',body)).entry;const duplicate=(await post('alice',body)).entry;assert.equal(payment.id,duplicate.id);await post('alice',draft('contribution','founder-3'),403);
 await post('alice',review(payment,due,'60'),403);await post('outsider',review(payment,due,'60'),403);const otherDue=data.entries.find(e=>e.type==='obligation'&&e.memberId==='founder-3');await post('bob',review(payment,otherDue,'60'),400);await post('bob',review(payment,due,'61'),400);
 payment=(await post('bob',review(payment,due,'60'))).entry;assert.equal(payment.status,'Verified');await post('owner',review(payment,due,'60','Owner reconciled'),403);
 data=await get('alice');assert.equal(obligationStanding(due,data.entries).remaining,4000);assert.equal(data.activity.filter(e=>e.entryId===payment.id&&e.kind==='submission').length,1);assert(data.activity.some(e=>e.entryId===payment.id&&e.title.includes('alice')&&e.status==='Verified'));assert(!JSON.stringify(data.activity).includes('PRIVATE-EVIDENCE'));assert(!JSON.stringify(data.activity).includes('PILOT-PRIVATE'));done('Partial contribution, duplicate retry, independent verification and correct remaining balance');
 let extra=(await post('alice',draft('contribution','founder-2','100.00'))).entry;extra=(await post('bob',review(extra,null,'0'))).entry;data=await get('alice');assert.equal(obligationStanding(due,data.entries).remaining,4000);assert.equal(obligationStanding(future,data.entries).remaining,25000);
 extra=(await post('bob',review(extra,due,'40'))).entry;data=await get('alice');assert.equal(obligationStanding(due,data.entries).remaining,0);assert.equal(obligationStanding(future,data.entries).remaining,25000);assert(!data.activity.some(e=>e.entryId===due.id&&e.kind==='overdue'));
 const staleReview=review(extra,due,'40');extra=(await post('bob',review(extra,null,'0','Rejected'))).entry;await post('bob',staleReview,409);data=await get('alice');assert.equal(obligationStanding(due,data.entries).remaining,4000);assert(data.activity.some(e=>e.entryId===due.id&&e.kind==='overdue'));assert.equal(extra.reviews.length,3);done('Extra capital, explicit allocation, correction history, stale review and overdue restoration');
 const rejected=data.entries.find(e=>e.id===extra.id);assert.equal(rejected.canResubmit,true);const correction={action:'resubmitContribution',entryId:rejected.id,reviewCount:rejected.reviews.length,title:rejected.title,memberId:rejected.memberId,amount:'95.00',currency:rejected.currency,date:rejected.date,method:rejected.method,reference:rejected.reference,purpose:rejected.purpose,submissionObligationId:'',reason:'Corrected the reported amount to match the receipt'};await post('bob',correction,403);extra=(await post('alice',correction)).entry;assert.equal(extra.status,'Awaiting verification');assert.equal(extra.amountMinor,9500);assert.equal(extra.corrections.length,1);assert.equal(extra.reviews.length,3);assert.equal(extra.canResubmit,false);await post('alice',correction,409);data=await get('alice');assert(data.activity.some(e=>e.entryId===extra.id&&e.kind==='correction'&&e.status==='Resubmitted'));extra=(await post('bob',review(extra,null,'0'))).entry;assert.equal(extra.status,'Verified');assert.equal(extra.reviews.length,4);data=await get('alice');const rejectedEvent=data.activity.find(e=>e.entryId===extra.id&&e.status==='Rejected'),correctedEvent=data.activity.find(e=>e.entryId===extra.id&&e.title.includes('corrected payment verified'));assert.match(rejectedEvent.description,/Reason: PRIVATE-EVIDENCE-REFERENCE/);assert.match(rejectedEvent.description,/\$100\.00 USD/);assert.match(correctedEvent.description,/previously rejected because: PRIVATE-EVIDENCE-REFERENCE/);assert.match(correctedEvent.description,/same payment record; no new contribution was created/);done('Rejected contribution can be corrected only by its submitter, resubmitted, audited and independently verified');
 const event=data.activity.find(e=>e.entryId===payment.id&&e.kind==='review');await post('alice',{action:'readActivity',eventIds:[event.id]});await post('alice',{action:'readActivity',eventIds:[event.id]});assert((await get('alice')).activity.find(e=>e.id===event.id).read);assert.equal((await get('bob')).activity.find(e=>e.id===event.id).read,false);await post('alice',{action:'readActivity',eventIds:['unknown-event']},409);done('Named Activity, persistent private read state and invalid-event rejection');
 let fx=(await post('alice',draft('contribution','founder-2','10.00','CAD'))).entry;await post('bob',review(fx,due,'10'),400);
 const onBehalf=(await post('owner',draft('contribution','founder-3','10'))).entry;await post('owner',review(onBehalf,null,'0'),403);await post('bob',review(onBehalf,null,'0'),403);await post('alice',review(onBehalf,null,'0'));
 await post('alice',draft('contribution','founder-2','0.001'),400);await post('alice',draft('contribution','founder-2','1.50','XAF'),400);done('Currency isolation, exact amounts, and neither submitter nor contributor can self-verify');
 let request=(await post('alice',draft('request','founder-2','500.00'))).entry;
 for(const who of ['owner','bob','carol']){request=(await post(who,{action:'approveRequest',entryId:request.id,token:request.funding.token})).entry;}
 assert.equal(request.status,'Authorized');assert.equal(request.funding.count,3);data=await get('alice');assert.equal(data.entries.find(e=>e.id===request.id).funding.count,3);
 await configure('carol',4,'Secretary',true,false);data=await get('alice');request=data.entries.find(e=>e.id===request.id);assert.equal(request.funding.count,2);assert.equal(request.status,'Awaiting approvals');await get('carol',403);
 request=(await post('alice',{action:'reviseRequest',entryId:request.id,token:request.funding.token,title:request.title,amount:'600.00',currency:'USD',reference:'Different masked recipient',purpose:request.purpose,date:request.date,reason:'Pilot recipient and amount change'})).entry;assert.equal(request.funding.count,0);assert.equal(request.fundingHistory[0].approvals.length,3);assert.equal(request.status,'Draft');done('Funding authorization, reload, revoked approver eligibility and changed-recipient reset');
 const final=await get('owner');assert.equal(final.organizations.length,1);assert.equal(final.entries.filter(e=>e.type==='obligation').length,16);assert.equal(final.entries.filter(e=>e.id===payment.id).length,1);assert.equal(sql.prepare('SELECT count(*) n FROM notification_reads').get().n,1);done('Final records reconcile with no duplicate organizations, payments, dues or read receipts');
 console.log('PILOT API PASS: '+passed+' scenarios. Browser/mobile and real-member acceptance are still pending.');
})().catch(e=>{console.error(e);process.exitCode=1;});
