const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript');
let state=[],cursor=0;const cache=new Map();function load(file){if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const req=name=>{if(name==='react')return {useState:initial=>{const i=cursor++;if(state[i]===undefined)state[i]=initial;return [state[i],next=>state[i]=typeof next==='function'?next(state[i]):next];}};if(name==='react/jsx-runtime')return {jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};if(name==='./record-time')return {RecordTime:'RecordTime'};return load(name.startsWith('@/')?name.slice(2)+'.ts':path.join(path.dirname(file),name+'.ts'));};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInThisContext('(function(require,module,exports){'+code+'\n})')(req,module,module.exports);return module.exports;}
function all(node,predicate,out=[]){if(Array.isArray(node)){for(const n of node)all(n,predicate,out);}else if(node&&typeof node==='object'){if(predicate(node))out.push(node);all(node.props?.children,predicate,out);}return out;}
const text=node=>typeof node==='string'||typeof node==='number'?String(node):Array.isArray(node)?node.map(text).join(''):node?.props?text(node.props.children):'';
const {receiptQueue}=load('lib/receipt-queue.ts'),Component=load('app/receipt-queue.tsx').default;
const org={id:'owner:mola',mode:'Shared ownership',permissions:{isOwner:true,canReview:true},members:[{id:'a',name:'Alex Example'}]};
const entry=(id,extra={})=>({id,orgId:org.id,type:'contribution',memberId:'a',title:id,amountMinor:10000,currency:'USD',status:'Awaiting verification',date:'2026-01-01',created:'2026-01-02T12:00:00Z',canReview:true,reference:'Receipt test',...extra});
const entries=[entry('new',{created:'2026-01-03T00:00:00Z'}),entry('old',{date:'2026-12-01',created:'2026-01-01T00:00:00Z'}),entry('self',{canReview:false,canOwnerReconcile:true}),entry('other reviewer',{canReview:false}),entry('provisional',{status:'Owner reconciled'}),entry('verified',{status:'Verified'}),entry('rejected',{status:'Rejected'}),entry('foreign',{orgId:'other:mola'}),entry('not contribution',{type:'obligation'})];
assert.deepEqual(receiptQueue(org,entries).rows.map(e=>e.id),['old','self','new']);assert.equal(receiptQueue(org,entries).pending,4);assert.equal(receiptQueue(org,entries).independent,2);assert.equal(receiptQueue(org,entries,'provisional').rows.length,1);assert.equal(entries[0].id,'new');
const calls=[];const props={org,entries,disabled:false,onReview:e=>calls.push('review:'+e.id),onOpen:e=>calls.push('open:'+e.id)};const render=extra=>{cursor=0;return Component({...props,...extra});};const buttons=tree=>all(tree,n=>n.type==='button');const click=(tree,label)=>{const b=buttons(tree).find(n=>text(n)===label);assert(b,label);b.props.onClick();};
let evidence=render({entries:[entry('attached',{hasReceipt:true,canViewReceipt:true,method:'Zelle (external)'})]});assert(text(evidence).includes('Screenshot attached · private'));assert(text(evidence).includes('Zelle (external)'));assert(text(evidence).includes('not confirmation that funds arrived'));click(evidence,'View screenshot & details');assert.equal(calls.at(-1),'open:attached');
evidence=render({entries:[entry('private',{hasReceipt:true,canViewReceipt:false,canReview:false})]});assert(!text(evidence).includes('View screenshot & details'));assert.equal(all(evidence,n=>n.type==='img'||n.type==='a').length,0);
evidence=render({entries:[entry('missing',{canUploadReceipt:true})]});assert(text(evidence).includes('No screenshot attached · optional'));click(evidence,'Add screenshot / details');assert.equal(calls.at(-1),'open:missing');
assert(text(render({entries:[]})).includes('No pending reviews'));state=[];
let tree=render();assert.equal(all(tree,n=>n.type==='article').length,4);assert(text(tree).includes('A different authorized reviewer is needed.'));assert(!text(tree).includes('foreign'));assert(!text(tree).includes('verified'));assert(text(tree).includes('Alex Example'));click(tree,'Review receipt');assert.equal(calls.at(-1),'review:old');click(tree,'Reconcile provisionally');assert.equal(calls.at(-1),'review:self');click(tree,'Open details');assert.equal(calls.at(-1),'open:old');
click(tree,'All pending (4)');tree=render();assert(text(tree).includes('A different authorized reviewer is needed.'));assert.equal(all(tree,n=>n.type==='article').length,4);
click(tree,'Owner reconciled (1)');tree=render();assert.equal(all(tree,n=>n.type==='article').length,1);assert(text(tree).includes('eligible different member'));const before=calls.length;for(const b of buttons(render({disabled:true})).filter(b=>['Review receipt','Open details'].includes(text(b)))){assert.equal(b.props.disabled,true);b.props.onClick();}assert.equal(calls.length,before);
state=[];assert.equal(render({org:{...org,mode:'Individual land allocations'}}),null);state=[];tree=render({org:{...org,permissions:{isOwner:false,canReview:false}},entries:[entry('own',{canReview:false,canOwnerReconcile:false})]});assert(text(tree).includes('A different authorized reviewer is needed.'));assert(!buttons(tree).some(b=>text(b)==='Review receipt'));
state=[];tree=render({entries:Array.from({length:17},(_,i)=>entry('row'+i))});assert.equal(all(tree,n=>n.type==='article').length,5);click(tree,'Show more (12 remaining)');tree=render({entries:Array.from({length:17},(_,i)=>entry('row'+i))});assert.equal(all(tree,n=>n.type==='article').length,15);
state=[];assert(text(render({entries:[]})).includes('No pending payment reports'));console.log('RECEIPT QUEUE PASS: scope, oldest submission order, status separation, per-entry permissions, actions, save guards, owner/reviewer visibility and pagination.');
const mixed=[entry('usd'),entry('cad',{currency:'CAD',amountMinor:75000}),entry('xaf',{currency:'XAF',amountMinor:323149}),entry('foreign',{orgId:'other'}),entry('done',{status:'Verified'})];
assert.deepEqual(receiptQueue(org,mixed,'pending').totals,[{currency:'CAD',count:1,amountMinor:75000},{currency:'USD',count:1,amountMinor:10000},{currency:'XAF',count:1,amountMinor:323149}]);
assert.equal(receiptQueue(org,[entry('huge',{amountMinor:Number.MAX_SAFE_INTEGER}),entry('extra')],'pending').totals[0].amountMinor,null);
state=[];tree=render({entries:Array.from({length:17},(_,i)=>entry('total'+i))});assert(text(tree).includes('$1,700'));assert(text(tree).includes('17 payments'));assert(text(tree).includes('not a confirmed bank balance'));assert.equal(all(tree,n=>n.type==='article').length,5);
click(tree,'Owner reconciled (0)');tree=render({entries:mixed});assert.equal(all(tree,n=>n.props?.['aria-label']==='Reported amounts in selected queue').length,0);
