const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript');
const root=path.resolve(__dirname,'..');let state=[],cursor=0,refs=[];const cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const req=name=>{if(name==='react')return {useState:initial=>{const i=cursor++;if(state[i]===undefined)state[i]=initial;return [state[i],next=>state[i]=typeof next==='function'?next(state[i]):next];},useRef:initial=>{const i=cursor++;return refs[i]||(refs[i]={current:initial});}};if(name==='react/jsx-runtime')return {jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};if(name==='@/lib/receipt-upload')return {uploadReceipt:async()=>{throw new Error('Upload is not used in this preview test.');}};if(name==='@/lib/receipt-url')return {receiptUrl:(orgId,entryId)=>'/api/receipt?'+new URLSearchParams({orgId,entryId})};if(name==='@/components/ui/dialog')return {Dialog:'Dialog',DialogContent:'DialogContent',DialogHeader:'DialogHeader',DialogTitle:'DialogTitle',DialogDescription:'DialogDescription'};return require(name);};vm.runInThisContext('(function(require,module,exports){'+source+'\n})',{filename:file})(req,module,module.exports);return module.exports;}
function find(node,predicate){if(Array.isArray(node)){for(const child of node){const hit=find(child,predicate);if(hit)return hit;}return null;}if(!node||typeof node!=='object')return null;if(predicate(node))return node;return find(node.props?.children,predicate);}
function all(node,predicate,out=[]){if(Array.isArray(node)){for(const child of node)all(child,predicate,out);}else if(node&&typeof node==='object'){if(predicate(node))out.push(node);all(node.props?.children,predicate,out);}return out;}
const Component=load(path.join(root,'app/receipt-attachment.tsx')).default;
const entry={id:'payment-1',orgId:'owner:mola',type:'contribution',title:'Weekly contribution',memberId:'founder-1',amountMinor:10000,currency:'USD',status:'Awaiting verification',date:'2026-10-10',created:'2026-10-10T12:00:00.000Z',hasReceipt:true,canViewReceipt:true,canUploadReceipt:false};
const render=()=>{cursor=0;return Component({entry});};let tree=render();
assert.equal(all(tree,node=>node.type==='a').length,0,'Screenshot must not open through a new-tab link');const button=find(tree,node=>node.type==='button'&&node.props.children==='View attached screenshot');assert(button);button.props.onClick();tree=render();const dialog=find(tree,node=>node.type==='Dialog');assert.equal(dialog.props.open,true);const image=find(tree,node=>node.type==='img');assert(image);assert.match(image.props.src,/^\/api\/receipt\?/);assert.match(image.props.src,/entryId=payment-1/);assert.equal(image.props.alt,'Payment screenshot for Weekly contribution');dialog.props.onOpenChange(false);assert.equal(find(render(),node=>node.type==='Dialog').props.open,false);
console.log('RECEIPT PREVIEW PASS: authorized evidence opens in an in-app dialog with no new-tab link and closes back to the payment record.');
