'use client';
import {useState} from 'react';
import type {ActivityEvent} from '@/lib/activity';
import {formatTimestamp} from '@/lib/deadlines';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Bell,CheckCheck} from 'lucide-react';
export function activityBadgeClass(status:string){return ['Rejected','Overdue','Behind'].includes(status)?'danger':status==='Verified'?'green':status==='Owner reconciled'?'neutral':status==='Resubmitted'?'resubmitted':'pending';}
export default function ActivityFeed({events,asOf,markRead,onOpen}:{events:ActivityEvent[];asOf:string;markRead:(ids:string[])=>Promise<void>;onOpen:(entryId:string,targetView?:'contributions')=>void}){
const [filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[limit,setLimit]=useState(50);
const filtered=events.filter(e=>filter==='unread'?!e.read:filter==='overdue'?e.kind==='overdue':true),shown=filtered.slice(0,limit),unread=events.filter(e=>!e.read).length;
async function read(ids:string[]){setBusy(true);setError('');try{for(let i=0;i<ids.length;i+=100)await markRead(ids.slice(i,i+100));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <section className="panel activity-panel"><div className="panel-header"><div><h2>Organization activity</h2><p className="muted">{unread} unread · Overdue balances as of {formatTimestamp(asOf)}</p></div><button className="secondary" disabled={busy||!unread} onClick={()=>read(events.filter(e=>!e.read).map(e=>e.id))}><CheckCheck size={17}/>{busy?'Saving…':'Mark all read'}</button></div><div className="activity-tabs"><Tabs value={filter} onValueChange={v=>{setFilter(v);setLimit(50);}}><TabsList><TabsTrigger value="all">All activity</TabsTrigger><TabsTrigger value="unread">Unread ({unread})</TabsTrigger><TabsTrigger value="overdue">Overdue ({events.filter(e=>e.kind==='overdue').length})</TabsTrigger></TabsList></Tabs></div><p className="activity-caption">In-app only. Updates refresh every 30 seconds while the workspace is open. You can also refresh manually. Review events are history; open the record for its current status. No email, text, or push messages are sent.</p>{error&&<p className="form-error" role="alert">{error}</p>}
{shown.length?shown.map(e=><article key={e.id} className={'activity-event '+(!e.read?'unread':'')}><span className="activity-symbol"><Bell size={19}/></span><div className="activity-body"><div className="activity-title"><h3>{e.title}</h3><span className={'badge '+activityBadgeClass(e.status)}>{e.status}</span>{!e.read&&<span className="unread-label">Unread</span>}</div><p>{e.description}</p><small>{e.kind==='overdue'?(e.deadline?'Recorded cutoff: '+formatTimestamp(e.deadline.at,e.deadline.timeZone):'Due date: '+e.at.slice(0,10)+' · Cutoff time not captured'):formatTimestamp(e.at)}</small><div className="activity-actions"><button className="text-button" onClick={()=>onOpen(e.entryId,e.targetView)}>{e.targetView?'View instructions':'Open record'}</button>{!e.read&&<button disabled={busy} className="text-button" onClick={()=>read([e.id])}>Mark read</button>}</div></div></article>):<div className="empty"><Bell size={28}/><h3>{filter==='unread'?'You’re caught up':filter==='overdue'?'No overdue recorded obligations':'No activity yet'}</h3><p>{filter==='all'?'Contributions, receipt reviews and external payment reports will appear here.':'Refresh to check the latest recorded information.'}</p></div>}
{filtered.length>shown.length&&<button className="secondary activity-more" onClick={()=>setLimit(n=>n+50)}>Show more ({filtered.length-shown.length} remaining)</button>}</section>;
}
