'use client';
import {RecordTime} from './record-time';
import {useState,useRef} from 'react';
import {saveWorkspaceRecord} from '@/lib/workspace-save';
import {toast} from 'sonner';
import {Settings2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {Org,Entry} from '@/lib/model';
export default function ApprovalPolicyPanel({org,requests,reload,onBusy}:{org:Org;requests:Entry[];reload:()=>Promise<void>;onBusy?:(busy:boolean)=>void}){
 const savingNow=useRef(false);
 const policy=org.approvalPolicy,configured=!!policy?.approverMemberIds,ids=policy?.approverMemberIds||[];
 const [form,setForm]=useState<{requiredApprovals:number;approverMemberIds:string[];reason:string;acknowledged:boolean;version:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const available=org.members.filter(m=>ids.includes(m.id)&&m.access?.enabled&&m.access.claimed).length;
 const withApprovals=requests.filter(r=>r.approvals?.length).length;
 const start=()=>{setError('');setForm({requiredApprovals:policy?.requiredApprovals||3,approverMemberIds:[...ids],reason:'',acknowledged:false,version:org.version});};
 async function save(e:React.FormEvent){e.preventDefault();if(!form||savingNow.current)return;savingNow.current=true;setBusy(true);onBusy?.(true);setError('');try{await saveWorkspaceRecord({...form,action:'approvalPolicy',orgId:org.id});setForm(null);toast.success('Internal approval rule saved.');try{await reload();}catch{toast.warning('The rule was saved, but the workspace could not refresh. Refresh before making another change.');}}catch(e){setError((e as Error).message);}finally{savingNow.current=false;setBusy(false);onBusy?.(false);}}
 const names=(memberIds:string[]|undefined)=>memberIds?memberIds.map(id=>org.members.find(m=>m.id===id)?.name||'Former founder').join(', '):'Pilot officer roles and workspace owner';
 return <section className="panel approval-policy-panel"><div className="panel-header"><div><h2>Funding approval rule</h2><p className="muted">{configured?'Configured internal rule':'Existing pilot rule'} · {policy?.requiredApprovals||3} distinct approvals{configured?' · Version '+policy?.version:''}</p></div>{org.permissions?.canManage&&<button className="secondary" onClick={start}><Settings2 size={17}/>{configured?'Change rule':'Configure rule'}</button>}</div><div className="approval-policy-body"><p><strong>Designated approvers:</strong> {names(configured?ids:undefined)}</p>{configured&&<p>{available} of {ids.length} designated founders have active linked accounts. A requester is excluded from approving their own request.</p>}{configured&&available<(policy?.requiredApprovals||3)&&<p className="form-note">There are not enough active linked approvers yet. Member setup can be completed under Members; this screen sends no invitations.</p>}<p className="muted">Saving records an internal rule and its reason. It does not collect founder votes, adopt a signed agreement, or change ownership weights. Bank execution stays external.</p>{!!policy?.history?.length&&<details className="policy-history"><summary>Rule change history ({policy.history.length})</summary>{[...policy.history].reverse().map((h,i)=><article className="review-event" key={i}><strong>{h.requiredApprovals} approvals{h.version?' · Version '+h.version:''}</strong><small><RecordTime at={h.at}/> · {h.actorName||'Workspace owner'}</small><p>Designated: {names(h.approverMemberIds)}</p>{h.previousRequired&&<p>Previous: {h.previousRequired} approvals · {names(h.previousApproverMemberIds)}</p>}<p>{h.reason||'Legacy rule record'}</p></article>)}</details>}</div>
 <Dialog open={!!form} onOpenChange={open=>{if(!open&&!savingNow.current)setForm(null);}}><DialogContent className="editor"><DialogHeader><DialogTitle>Configure funding approvals</DialogTitle><DialogDescription>Applies immediately after saving. Requests with earlier approvals require a fresh version before review resumes.</DialogDescription></DialogHeader>{form&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0,display:'grid',gap:15}}><label className="field">Required distinct approvals<Select value={String(form.requiredApprovals)} onValueChange={v=>setForm({...form,requiredApprovals:Number(v)})}><SelectTrigger className="choice" aria-label="Required approvals"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:Math.max(0,org.members.length-2)},(_,i)=>i+2).map(n=><SelectItem key={n} value={String(n)}>{n} founders</SelectItem>)}</SelectContent></Select></label><fieldset className="policy-founders"><legend>Designated founders · {form.approverMemberIds.length} selected</legend>{org.members.map(m=><label className="check-field" key={m.id}><Checkbox checked={form.approverMemberIds.includes(m.id)} onCheckedChange={v=>setForm({...form,approverMemberIds:v===true?[...form.approverMemberIds,m.id]:form.approverMemberIds.filter(id=>id!==m.id)})}/><span><strong>{m.name}</strong><small>{m.access?.enabled&&m.access.claimed?'Active linked account':m.access?.enabled?'Awaiting first sign-in':'Account setup needed'}</small></span></label>)}</fieldset><p className="form-note">Choose at least {form.requiredApprovals} founders. If a selected founder submits a request, that person cannot approve it. Selecting more than the minimum leaves room for a requester or an unavailable member. The workspace owner must also be selected and have a linked founder account to approve under this rule.</p><label className="field">Decision reference / reason<textarea required minLength={5} maxLength={2000} rows={3} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Meeting reference or reason for the configuration"/></label><label className="check-field"><Checkbox checked={form.acknowledged} onCheckedChange={v=>setForm({...form,acknowledged:v===true})}/><span>I understand this takes effect immediately and existing approvals must be reviewed again. {withApprovals} request(s) currently have recorded approvals.</span></label>{error&&<div role="alert"><p className="form-error">{error}</p>{error.includes("session has expired")&&<a className="text-button" href="/auth" target="_blank" rel="noreferrer">Sign in in another tab</a>}</div>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setForm(null)}>Cancel</button><button type="submit" className="primary" disabled={busy||!form.acknowledged||form.approverMemberIds.length<form.requiredApprovals}>{busy?'Saving…':'Save internal rule'}</button></div></fieldset></form>}</DialogContent></Dialog>
 </section>;
}
