'use client';
import {useRef,useState} from 'react';
import {type Org} from '@/lib/model';
import {saveWorkspaceRecord} from '@/lib/workspace-save';
import {RecordTime} from './record-time';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function CollectionInstructions({org,disabled,onBusy,onSaved}:{org:Org;disabled:boolean;onBusy:(busy:boolean)=>void;onSaved:(org:Org)=>void}){
 const latch=useRef(false);
 const [draft,setDraft]=useState<{version:number;text:string;reason:string;acknowledged:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(org.mode!=='Shared ownership')return null;
 const current=org.collectionInstructions,latest=current?.history.at(-1);
 const edit=()=>{if(latch.current||disabled)return;setError('');setDraft({version:org.version,text:current?.text||'',reason:'',acknowledged:false});};
 async function save(e:React.FormEvent){e.preventDefault();if(latch.current||!draft)return;latch.current=true;setBusy(true);onBusy(true);setError('');try{
  const result=await saveWorkspaceRecord({...draft,orgId:org.id,action:'collectionInstructions'});onSaved(result.organization);setDraft(null);
 }catch(e){setError((e as Error).message);}finally{latch.current=false;setBusy(false);onBusy(false);}}
 return <section className="panel collection-instructions"><div className="panel-header"><div><h2>How to contribute</h2><p className="muted">Instructions recorded by your group. Payment happens outside this app.</p></div>{org.permissions?.isOwner&&<button className="secondary" type="button" disabled={disabled||busy} onClick={edit}>{current?.text?'Update instructions':'Add instructions'}</button>}</div><div className="collection-instructions-body">{current?.text?<p className="prewrap">{current.text}</p>:<p className="muted">No contribution instructions have been recorded. Ask the group for confirmed payment details before sending money.</p>}{latest&&<p className="collection-instructions-meta">Updated by {latest.actorName} · <RecordTime at={latest.at}/></p>}<p className="form-note">These instructions do not verify a bank account or activate a payment method. Confirm unfamiliar or changed destination details with the group before paying.</p></div>
 {!!current?.history.length&&<details className="collection-instructions-history"><summary>Instruction history · {current.history.length} changes</summary>{[...current.history].reverse().map(h=><article key={h.version}><strong>{h.actorName} · <RecordTime at={h.at}/></strong><p>Reason: {h.reason}</p><p className="prewrap">{h.text||'Instructions cleared'}</p></article>)}</details>}
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!latch.current)setDraft(null);}}><DialogContent className="editor"><DialogHeader><DialogTitle>Contribution instructions</DialogTitle><DialogDescription>Record the group’s agreed external payment instructions. Members can see the current instructions and the change history.</DialogDescription></DialogHeader>{draft&&<form onSubmit={save}><fieldset disabled={busy} className="payout-fields"><label className="field">Instructions for members<textarea rows={7} maxLength={3000} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label><p className="form-note">Use agreed payment methods, recipient contact details and masked account labels. Do not include passwords, full bank account numbers or identity documents. Leave the instructions empty to clear them; prior versions remain in history.</p><label className="field">Reason for this change<textarea rows={3} required minLength={5} maxLength={1000} value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label><label className="payout-consent"><input type="checkbox" required checked={draft.acknowledged} onChange={e=>setDraft({...draft,acknowledged:e.target.checked})}/><span>I have checked these instructions with the group and understand that members can see the details and change history.</span></label>{error&&<div role="alert"><p className="form-error">{error}</p>{error.includes('session has expired')&&<a className="text-button" href="/auth" target="_blank" rel="noreferrer">Sign in in another tab</a>}</div>}<div className="form-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>{if(!latch.current)setDraft(null);}}>Cancel</button><button className="primary" disabled={busy||!draft.acknowledged||draft.reason.trim().length<5}>{busy?'Saving…':'Save instructions'}</button></div></fieldset></form>}</DialogContent></Dialog>
 </section>;
}
