'use client';
import {ArrowUpRight,Target,Wallet,Clock3,Users,Lightbulb} from 'lucide-react';
import {type Org,type Entry,money} from '@/lib/model';
import {founderSummary,goalProgress} from '@/lib/founder-hub';
import MemberOverview from './member-overview';
import {RecordTime} from './record-time';
export default function FounderHub({org,entries,asOf,disabled,onNavigate,onOpen}:{org:Org;entries:Entry[];asOf:string;disabled:boolean;onNavigate:(view:string)=>void;onOpen:(entry:Entry)=>void}){
 const summary=founderSummary(org,entries,asOf||undefined),checkpoint=org.cashCheckpoints?.at(-1),goals=(org.savingsGoals||[]).filter(g=>g.status!=='Archived'),goal=goals.find(g=>g.status==='Active')||goals[0],progress=goal?goalProgress(goal,entries,org.id):null;
 const pending=entries.filter(e=>e.type==='contribution'&&e.status==='Awaiting verification'),opportunities=entries.filter(e=>e.type==='opportunity'),recent=entries.filter(e=>e.type==='contribution').slice(0,5);
 return <div className="founder-home">
  <section className="capital-hero" aria-labelledby="capital-title"><div className="capital-hero-copy"><span className="eyebrow">BUILDING TOGETHER</span><h2 id="capital-title">Small commitments.<br/>A bigger future.</h2><p>{org.members.length} founders. One shared record of the capital you build and the decisions you make.</p><div className="hero-actions"><button className="secondary" disabled={disabled} onClick={()=>onNavigate('goals')}>Explore savings goals <ArrowUpRight size={16}/></button><span>{money(summary.weekly,org.currency)} / founder / week</span></div></div><div className="capital-total"><span>VERIFIED CONTRIBUTIONS · {org.currency}</span><strong>{money(summary.verified,org.currency)}</strong><p>Independently reviewed contributions across all recorded dates.</p><div className="capital-total-foot"><span>Group weekly expectation</span><b>{money(summary.weekly*org.members.length,org.currency)}</b></div></div></section>
  <div className="hub-metrics"><section className="hub-metric"><Wallet size={20}/><span>Bank balance checkpoint</span><strong>{checkpoint?money(checkpoint.amountMinor,checkpoint.currency):'Not recorded'}</strong><small>{checkpoint?`Human checked · ${checkpoint.asOf}`:'Record a dated balance after checking the bank.'}</small><button className="text-button" disabled={disabled} onClick={()=>onNavigate('goals')}>View checkpoints <ArrowUpRight size={14}/></button></section><section className="hub-metric"><Clock3 size={20}/><span>Awaiting verification</span><strong>{money(summary.pending,org.currency)}</strong><small>{pending.length} pending payment record{pending.length===1?'':'s'} · all currencies</small><button className="text-button" disabled={disabled} onClick={()=>onNavigate('contributions')}>View contributions <ArrowUpRight size={14}/></button></section><section className="hub-metric"><Users size={20}/><span>Reported spending</span><strong>{money(summary.spending,org.currency)}</strong><small>External payout reports, including fees.</small><button className="text-button" disabled={disabled} onClick={()=>onNavigate('statements')}>Group statement <ArrowUpRight size={14}/></button></section></div>
  {summary.provisional>0&&<p className="hub-caption">{money(summary.provisional,org.currency)} in provisional owner-reconciled contributions is excluded from verified capital.</p>}
  <MemberOverview org={org} entries={entries} disabled={disabled} onStatement={()=>onNavigate('statements')} onSetup={()=>onNavigate('members')} onOpen={onOpen}/>
  <section className="panel savings-highlight"><div className="panel-header"><div><span className="eyebrow">SHARED DIRECTION</span><h2>{goal?.title||'Your first capital goal'}</h2></div><Target size={21}/></div><div className="hub-panel-body">{goal&&progress?<><div className="goal-big-number">{money(progress.verified,goal.currency)} <small>of {money(goal.targetMinor,goal.currency)}</small></div><progress max="100" value={progress.percent} aria-label={`${goal.title} contribution progress`}/><div className="goal-meta"><span>{progress.percent.toFixed(1)}% contributed</span><span>Target {goal.targetDate}</span></div><p>{goal.status==='Planning'?'Planning target':progress.onTrack?'On track against a straight-line contribution plan':'Behind the straight-line contribution plan'} · contributions since {goal.startDate}.</p></>:<><h3>Give your weekly commitments a destination.</h3><p>Create a shared savings target and explore how different contribution schedules could get you there.</p></>}<button className="secondary" disabled={disabled} onClick={()=>onNavigate('goals')}>{goal?'Open savings & planning':'Set the first goal'} <ArrowUpRight size={15}/></button><small className="hub-caption">Goal progress measures verified contributions. It does not reserve cash.</small></div></section>
  <div className="hub-two-column"><section className="panel"><div className="panel-header"><h2>Recent contributions</h2><button className="text-button" onClick={()=>onNavigate('contributions')}>View all <ArrowUpRight size={15}/></button></div>{recent.length?<div className="founder-list">{recent.map(entry=><button key={entry.id} className="recent-payment" disabled={disabled} onClick={()=>onOpen(entry)}><div><strong>{org.members.find(m=>m.id===entry.memberId)?.name||'Founder'}</strong><small>{entry.date} · {entry.title}</small></div><div><b>{money(entry.amountMinor,entry.currency)}</b><span className={'badge '+(entry.status==='Verified'?'green':entry.status==='Rejected'?'danger':'pending')}>{entry.status}</span></div></button>)}</div>:<div className="empty compact"><p>Your first payment will appear here after submission.</p></div>}</section><section className="hub-next"><button disabled={disabled} onClick={()=>onNavigate('opportunities')}><Lightbulb size={24}/><div><h3>Explore possibilities</h3><p>{opportunities.length?`${opportunities.length} ideas in your shared opportunity register.`:'Save a SaaS idea, property or business opportunity for discussion.'}</p></div><ArrowUpRight size={18}/></button><p className="hub-caption">Workspace loaded <RecordTime at={asOf}/> · forecasts and investment ideas are separate from actual funds.</p></section></div>
 </div>;
}
