'use client';
import {RecordTime} from './record-time';
import {useState,useRef} from 'react';
import {saveWorkspaceRecord} from '@/lib/workspace-save';
import {ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Org,Entry,money} from '@/lib/model';
import ApprovalPolicyPanel from './approval-policy';
import ExternalPayouts from './external-payouts';
import {payoutTotals} from '@/lib/payouts';
export default function FundingRequests({org,requests,reload,onBusy}:{org:Org;requests:Entry[];reload:()=>Promise<void>;onBusy?:(busy:boolean)=>void}){
 const savingNow=useRef(false);
 const [selected,setSelected]=useState<Entry|null>(null),[edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const lock=(value:boolean)=>{savingNow.current=value;setBusy(value);onBusy?.(value);};
 const state=selected?.funding;
 const open=(entry:Entry)=>{if(savingNow.current)return;setSelected(entry);setEdit(null);setError('');};
 async function mutate(action:string){if(!selected||savingNow.current)return;lock(true);setError('');try{
  const data=await saveWorkspaceRecord({...edit,action,orgId:org.id,entryId:selected.id,token:selected.funding?.token});
  setSelected(data.entry);setEdit(null);
  try{await reload();}catch{setError('Your change was saved, but the request list could not refresh. Refresh the workspace before taking another action.');}
 }catch(e){setError((e as Error).message);}finally{lock(false);}}
 const beginEdit=()=>{if(!selected)return;setError('');setEdit({title:selected.title,amount:String(selected.amountMinor/(selected.currency==='XAF'?1:100)),currency:selected.currency,date:selected.date,reference:selected.reference,purpose:selected.purpose,reason:''});};
 const field=(key:string,label:string,type='text')=><label className="field">{label}<input required type={type} maxLength={180} value={edit[key]} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>;
 return <>
 <ApprovalPolicyPanel org={org} requests={requests} reload={reload} onBusy={lock}/>
 <details className="panel hub-panel-body"><summary>How funding approvals work</summary><p>Requesters cannot approve their own requests. Revisions require fresh approvals. Internal authorization does not transfer money or replace an investment vote.</p></details>
 {requests.length?<section className="panel"><div className="panel-header"><h2>Funding requests</h2><span className="badge neutral">{requests.length} records</span></div>{requests.map(e=><button className="funding-row" key={e.id} onClick={()=>open(e)}><span className="empty-icon"><ShieldCheck size={22}/></span><div><h3>{e.title}</h3><p>{e.reference||'Recipient reference needed'}</p><small>{e.date} · Version {e.funding?.revision||1} · {e.funding?.count||0}/{e.funding?.required||3} approvals</small></div><div className="funding-amount"><strong>{money(e.amountMinor,e.currency)} {e.currency}</strong><span className={'badge '+(e.status==='Authorized'?'green':e.status==='Draft'?'neutral':'pending')}>{e.status==='Authorized'?'Internally authorized':e.status}</span>{e.payouts?.length?<small>{money(payoutTotals(e).total,e.currency)} {e.currency} spending reported · {money(payoutTotals(e).remaining,e.currency)} unreported</small>:<small>No external payments reported</small>}</div></button>)}</section>:<section className="panel empty"><ShieldCheck size={28}/><h3>No funding requests yet</h3><p>Record an amount, recipient reference, and investment purpose for review.</p></section>}
 <Dialog open={!!selected} onOpenChange={v=>{if(!v&&!savingNow.current){setSelected(null);setEdit(null);setError('');}}}><DialogContent className="editor"><DialogHeader><DialogTitle>{edit?'Revise funding request':selected?.title}</DialogTitle><DialogDescription>{edit?'Saving starts a new version and clears all current approvals. The previous version stays in history.':`Version ${state?.revision||1} · Internal approval only · Bank execution external`}</DialogDescription></DialogHeader>
 {selected&&(edit?<form onSubmit={e=>{e.preventDefault();void mutate('reviseRequest');}}><fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0,display:'grid',gap:15}}>{field('title','Request title')}<div className="form-grid">{field('amount','Requested amount')}<label className="field">Currency<Select value={edit.currency} onValueChange={currency=>setEdit({...edit,currency})}><SelectTrigger className="choice"><SelectValue/></SelectTrigger><SelectContent>{['USD','CAD','XAF'].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label></div>{field('date','Request date','date')}{field('reference','Recipient / destination reference')}<label className="field">Purpose<textarea required maxLength={5000} rows={4} value={edit.purpose} onChange={e=>setEdit({...edit,purpose:e.target.value})}/></label><label className="field">Reason for revision<textarea required minLength={5} maxLength={2000} rows={2} value={edit.reason} onChange={e=>setEdit({...edit,reason:e.target.value})}/></label><p className="form-note">Use a recipient name and masked destination reference. Do not enter full account numbers. Even if the details stay the same, saving restarts approval collection.</p>{error&&<div role="alert"><p className="form-error">{error}</p>{error.includes("session has expired")&&<a className="text-button" href="/auth" target="_blank" rel="noreferrer">Sign in in another tab</a>}</div>}<div className="form-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>{setEdit(null);setError('');}}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save version & reset approvals'}</button></div></fieldset></form>:<div className="detail">
 <div className="funding-summary"><strong>{money(selected.amountMinor,selected.currency)} {selected.currency}</strong><span className={'badge '+(selected.status==='Authorized'?'green':'neutral')}>{selected.status==='Authorized'?'Internally authorized':selected.status}</span><p>{state?.count||0} of {state?.required||3} eligible approvals</p></div>
 <dl><dt>Requested by</dt><dd>{selected.submittedName||'Workspace owner'}</dd><dt>Recipient reference</dt><dd>{selected.reference||'Not supplied'}</dd><dt>Request date</dt><dd>{selected.date}</dd><dt>Recorded at (UTC)</dt><dd><RecordTime at={selected.created}/></dd></dl><h3>Investment purpose</h3><p className="prewrap">{selected.purpose||'Not supplied'}</p>
 {state?.needsRestart&&<p className="form-error">Earlier approvals are not bound to the current request or rule. The requester or owner must save a fresh version before approval collection resumes.</p>}
 {state&&state.availableApprovers<state.required&&<p className="form-note">Only {state.availableApprovers} eligible linked approver accounts are available for this request; {state.required} are required. The requester is excluded. Ask the owner to review member setup or the designated approver rule.</p>}
 <h3>Recorded approvals</h3><p className="muted">Only eligible approvers for this version count toward the total. Rule or account changes can affect eligibility.</p>{selected.approvals?.length?selected.approvals.map((a,i)=><div className="review-event" key={i}><strong>{a.actorName}</strong><small><RecordTime at={a.at}/></small></div>):<p className="muted">No approvals recorded for this version.</p>}
 {state?.approvedByMe&&<p className="form-note">Your approval is recorded.</p>}
 {error&&<div role="alert"><p className="form-error">{error}</p>{error.includes("session has expired")&&<a className="text-button" href="/auth" target="_blank" rel="noreferrer">Sign in in another tab</a>}</div>}
 <div className="form-actions">{state?.canEdit&&<button className="secondary" disabled={busy} onClick={beginEdit}>Revise / restart approvals</button>}{selected.canApprove&&<button className="primary" disabled={busy} onClick={()=>void mutate('approveRequest')}>{busy?'Saving…':'Approve this version'}</button>}</div>
 <ExternalPayouts key={selected.id} org={org} request={selected} onBusy={lock} onSaved={setSelected} reload={reload}/>
 <h3>Previous versions</h3>{selected.fundingHistory?.length?[...selected.fundingHistory].reverse().map((h,i)=><details className="funding-history" key={i}><summary>Version {h.revision} · {money(h.amountMinor,h.currency)} {h.currency} · {h.approvals.length} archived approvals</summary><p>{h.title}</p><p>Recipient: {h.reference||'Not supplied'}</p><p>Purpose: {h.purpose||'Not supplied'}</p><p>Revised by {h.actorName} · <RecordTime at={h.at}/></p><p>Reason: {h.reason}</p>{h.approvals.map((a,j)=><p key={j}>{a.actorName} approved · <RecordTime at={a.at}/></p>)}</details>):<p className="muted">This is the first recorded version.</p>}
 </div>)}
 </DialogContent></Dialog>
 </>;
}
