'use client';
import {RecordTime} from './record-time';
import {useState} from 'react';
import {Scale,Plus} from 'lucide-react';
import {Org,Entry} from '@/lib/model';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export default function Governance({org,decisions,reload,onCreate}:{org:Org;decisions:Entry[];reload:()=>Promise<void>;onCreate:()=>void}){
 const [filter,setFilter]=useState('all');const filtered=decisions.filter(d=>filter==='all'||d.status===filter);
 return <section className="panel governance-panel"><div className="panel-header"><div><h2>Governance decision register</h2><p className="muted">Record what the group discussed or adopted. These records do not change ownership, voting weights, or approvals automatically.</p></div><button className="secondary" onClick={onCreate}><Plus size={17}/>Record decision</button></div><div className="governance-toolbar"><label className="field">Status<Select value={filter} onValueChange={setFilter}><SelectTrigger className="choice" aria-label="Decision status"><SelectValue/></SelectTrigger><SelectContent>{['all','Draft','Proposed','Adopted','Superseded'].map(s=><SelectItem key={s} value={s}>{s==='all'?'All decisions':s}</SelectItem>)}</SelectContent></Select></label><p className="muted">{filtered.length} of {decisions.length} records</p></div>{filtered.length?filtered.map(d=><article className="decision-record" key={d.id}><div className="decision-heading"><div><span className="badge neutral">{d.decisionType||'Governance'}</span><h3>{d.title}</h3></div><span className={'badge '+(d.status==='Adopted'?'green':d.status==='Superseded'?'neutral':'pending')}>{d.status}</span></div><dl><dt>Decision date</dt><dd>{d.date}</dd><dt>Recorded at (UTC)</dt><dd><RecordTime at={d.created}/></dd><dt>Meeting / reference</dt><dd>{d.reference||'Not supplied'}</dd></dl><p className="prewrap">{d.purpose}</p>{d.status==='Adopted'&&<p className="form-note"><strong>Recorded as adopted.</strong> A separate implementation step is required before this changes units, weighted votes, approval thresholds, or payment behavior.</p>}</article>):<div className="empty"><Scale size={29}/><h3>{decisions.length?'No matching decisions':'No governance decisions recorded'}</h3><p>{decisions.length?'Try another status filter.':'Capture a valuation, ownership, voting, or reserved-decision proposal from a group meeting.'}</p><button className="secondary" onClick={onCreate}><Plus size={17}/>Record decision</button></div>}</section>;
}
