'use client';
import {RecordTime} from './record-time';
import type {ReactNode} from 'react';
import {Org,Member} from '@/lib/model';
import {memberReadiness} from '@/lib/pilot-setup';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
export default function MemberAccess({org,onEdit,ownerSetup}:{org:Org;onEdit:(member:Member)=>void;ownerSetup?:ReactNode}){
const owner=org.permissions?.isOwner;
const readiness=memberReadiness(org);
const {enabled,linked,reviewers}=readiness;
const next=org.members.find(m=>!m.access?.enabled||!m.access.email);
return <section className="panel access-panel"><div className="panel-header"><div><h2>Member accounts & permissions</h2><p className="muted">All {org.members.length} members remain founders. Officer roles do not change voting weight.</p></div><span className="badge neutral">Mola pilot</span></div>{ownerSetup}{owner&&<div className="member-setup"><div className="member-setup-summary" aria-label="Member setup progress"><div><span>Access enabled</span><strong>{enabled} <small>of {org.members.length}</small></strong></div><div><span>Accounts linked</span><strong>{linked} <small>of {org.members.length}</small></strong></div><div><span>Active reviewers</span><strong>{reviewers}</strong></div></div><p>{!readiness.independentReviewConfigured?'Independent review needs at least two linked member accounts and one authorized reviewer. A contributor or submitter cannot verify their own payment.':'Member linking is available for an independent review check. A contributor and a different authorized reviewer can use the pilot. First-use testing is deferred.'}</p>{next&&<button className="secondary" type="button" onClick={()=>onEdit(next)}>Configure next founder</button>}</div>}{owner&&<div className="notice"><p>Enter each member’s name and the email they use to sign in. Enable their app access and assign review permission where agreed. Website sharing must also allow that person before they can open this private site. Saving here sends no invitation. Set up your own founder slot too; the workspace owner retains setup permissions.</p></div>}
<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Founder</TableHead><TableHead>Officer role</TableHead><TableHead>Account</TableHead><TableHead>Payment reviews</TableHead>{owner&&<TableHead/>}</TableRow></TableHeader><TableBody>{org.members.map(m=><TableRow key={m.id}><TableCell><strong>{m.name}</strong>{org.permissions?.memberId===m.id&&<small>Your account</small>}</TableCell><TableCell>{m.role==='Name pending'?'Not assigned':m.role}</TableCell><TableCell><span className="badge neutral">{!m.access?'Not configured':!m.access?.enabled?'Disabled':m.access?.claimed?'Account linked':'Awaiting first sign-in'}</span>{owner&&<small>{m.access?.email||'No sign-in email'}</small>}</TableCell><TableCell>{m.access?.enabled&&m.access.canReview?'May verify others’ payments':'No review permission'}</TableCell>{owner&&<TableCell><button className="text-button" onClick={()=>onEdit(m)}>Configure</button></TableCell>}</TableRow>)}</TableBody></Table></div>
{owner&&!!org.accessHistory?.length&&<details className="access-history"><summary>Access change history</summary>{[...org.accessHistory].reverse().map((h,i)=><div className="review-event" key={i}><strong>{org.members.find(m=>m.id===h.memberId)?.name||'Member'}</strong><small><RecordTime at={h.at}/></small><p>{h.summary}</p></div>)}</details>}</section>;
}
