'use client';
import {useState} from 'react';
import {Download,FileText} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Org,Entry,money} from '@/lib/model';
import {memberStatement,statementCsv,type MemberStatement} from '@/lib/statements';
import {RecordTime,DeadlineTime,SubmissionTiming} from './record-time';
import {formatTimestamp} from '@/lib/deadlines';
export default function MemberStatements({org,entries,onOpen}:{org:Org;entries:Entry[];onOpen:(e:Entry)=>void}){
 const [memberId,setMemberId]=useState(org.permissions?.memberId||org.members[0]?.id||''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[limit,setLimit]=useState(50);
 let statement:MemberStatement|undefined,error='';try{statement=memberStatement(org,entries,memberId,from,to);}catch(e){error=(e as Error).message;}
 const reset=()=>{setFrom('');setTo('');setLimit(50);};
 const download=()=>{if(!statement)return;const blob=new Blob([statementCsv(org,statement)],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mola-statement-'+statement.member.name.replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,70)+'-'+(from||'all')+'-'+(to||'current')+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const badge=(status:string)=><span className={'badge '+(['Rejected','Behind','Overdue'].includes(status)?'danger':status==='Verified'||status==='Covered'?'green':status==='Owner reconciled'?'neutral':'pending')}>{status}</span>;
 return <>
 <section className="panel statement-controls"><div className="panel-header"><div><h2>Member statement</h2><p className="muted">All recorded dates by default. Amounts stay separate by currency.</p></div><button className="secondary" disabled={!statement} onClick={download}><Download size={17}/>Download CSV</button></div><div className="statement-filters"><label className="field">Member<Select value={memberId} onValueChange={id=>{setMemberId(id);setLimit(50);}}><SelectTrigger className="choice" aria-label="Statement member"><SelectValue/></SelectTrigger><SelectContent>{org.members.map(m=><SelectItem value={m.id} key={m.id}>{m.name}</SelectItem>)}</SelectContent></Select></label><label className="field">Payment / due date from<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setLimit(50);}}/></label><label className="field">Payment / due date to<input type="date" value={to} onChange={e=>{setTo(e.target.value);setLimit(50);}}/></label><button className="secondary" disabled={!from&&!to} onClick={reset}>All dates</button></div>{error&&<p className="form-error statement-error" role="alert">{error}</p>}</section>
 {statement&&<><div className="notice"><FileText size={19}/><p><strong>{statement.member.name} · {from||'First recorded date'} to {to||'Latest recorded date'}</strong><br/>Current loaded review status, not a historical closing balance. Payments use their payment date; obligations use their due date. Current credits from payments on any date reduce selected obligations. Refresh the workspace for updates.</p></div>
 {!statement.summaries.length?<section className="panel empty"><FileText size={28}/><h3>No records for this selection</h3><p>There are no payments or obligations for this member in the selected range. This does not confirm that nothing is owed.</p>{(from||to)&&<button className="secondary" onClick={reset}>Show all dates</button>}</section>:statement.summaries.map(s=><section className="panel statement-summary" key={s.currency}><div className="panel-header"><h2>{s.currency} · selected records</h2><span className="badge neutral">Current status</span></div><div className="statement-columns"><div><h3>Contributions</h3><dl><dt>Verified</dt><dd>{money(s.verified,s.currency)}</dd><dt>Pending verification</dt><dd>{money(s.pending,s.currency)}</dd><dt>Owner reconciled · provisional</dt><dd>{money(s.owner,s.currency)}</dd><dt>Rejected</dt><dd className={s.rejected>0?'overdue-amount':undefined}>{money(s.rejected,s.currency)}</dd></dl><h3>Unallocated reviewed contributions</h3><dl><dt>Verified, not assigned to dues</dt><dd>{money(s.verifiedUnallocated,s.currency)}</dd><dt>Owner reconciled, not assigned</dt><dd>{money(s.ownerUnallocated,s.currency)}</dd></dl><p className="muted">Unallocated amounts do not automatically cover future dues or create ownership units.</p></div><div><h3>Recorded obligations</h3>{s.dueCount?<><dl><dt>Agreed dues</dt><dd>{money(s.due,s.currency)}</dd><dt>Current assigned credit</dt><dd>{money(s.credited,s.currency)}</dd><dt>Remaining</dt><dd className="statement-remaining">{money(s.remaining,s.currency)}</dd><dt>Overdue portion</dt><dd className={s.overdue>0?'overdue-amount':undefined}>{money(s.overdue,s.currency)}</dd>{s.excess>0&&<><dt>Excess assigned credit</dt><dd>{money(s.excess,s.currency)}</dd></>}</dl><p className="muted">Credits include provisional owner reconciliation. Overdue is assessed at {formatTimestamp(statement!.today)} using each recorded cutoff. Earlier obligations without a cutoff use their due date. Excess on one obligation is not moved to another.</p></>:<p className="form-note">No {s.currency} obligations recorded in this range. A remaining balance cannot be inferred.</p>}</div></div></section>)}
 <section className="panel statement-section"><div className="panel-header"><h2>Payments · {statement.payments.length}</h2><span className="muted">Open a record for evidence and corrections</span></div>{statement.payments.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Payment date / label</TableHead><TableHead>Amount</TableHead><TableHead>Recorded at (UTC)</TableHead><TableHead>Captured cutoff / timing</TableHead><TableHead>Current status</TableHead><TableHead>Receipt reference</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{statement.payments.slice(0,limit).map(e=><TableRow key={e.id}><TableCell><strong>{e.date}</strong><small>{e.title}</small></TableCell><TableCell>{money(e.amountMinor,e.currency)} {e.currency}</TableCell><TableCell><RecordTime at={e.created}/></TableCell><TableCell>{e.submissionDeadline&&<RecordTime at={e.submissionDeadline.at} zone={e.submissionDeadline.timeZone}/>}<SubmissionTiming entry={e}/></TableCell><TableCell>{badge(e.status)}</TableCell><TableCell>{e.reference||'Not supplied'}</TableCell><TableCell><button className="text-button" onClick={()=>onOpen(e)}>Open record</button></TableCell></TableRow>)}</TableBody></Table></div>:<div className="empty compact"><p>No payments in this range.</p></div>}</section>
 <section className="panel statement-section"><div className="panel-header"><h2>Obligations · {statement.dues.length}</h2></div>{statement.dues.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Due date / obligation</TableHead><TableHead>Agreed amount</TableHead><TableHead>Current credit</TableHead><TableHead>Remaining</TableHead><TableHead>Standing</TableHead></TableRow></TableHeader><TableBody>{statement.dues.slice(0,limit).map(d=><TableRow key={d.entry.id}><TableCell><button className="text-button" onClick={()=>onOpen(d.entry)}>{d.entry.date}</button><small>{d.entry.title}</small><DeadlineTime entry={d.entry}/></TableCell><TableCell>{money(d.entry.amountMinor,d.entry.currency)} {d.entry.currency}</TableCell><TableCell>{money(d.credit,d.entry.currency)} {d.excess>0&&<small>Excess: {money(d.excess,d.entry.currency)}</small>}</TableCell><TableCell>{money(d.remaining,d.entry.currency)}</TableCell><TableCell>{badge(d.status)}</TableCell></TableRow>)}</TableBody></Table></div>:<div className="empty compact"><p>No obligations in this range.</p></div>}</section>
 <section className="panel statement-section"><div className="panel-header"><h2>Review & correction history · {statement.reviews.length}</h2></div><p className="statement-caption">All reviews of the selected payments, including reviews after the selected date range. Earlier credits are history and must not be added together.</p>{statement.reviews.slice(0,limit).map(({payment,review,index})=><div className="statement-review" key={payment.id+':'+index}><div>{badge(review.outcome)}<strong>{payment.title}</strong><small><RecordTime at={review.at}/> · {review.actorName||'Workspace owner'}</small></div><p>{review.evidence}</p>{review.obligationId&&<p>Credit in this review: {money(review.creditMinor,payment.currency)} {payment.currency}</p>}<button className="text-button" onClick={()=>onOpen(payment)}>Open payment</button></div>)}{!statement.reviews.length&&<div className="empty compact"><p>No reviews for these payments.</p></div>}</section>
 {Math.max(statement.payments.length,statement.dues.length,statement.reviews.length)>limit&&<div className="statement-more"><p className="muted">Showing up to {limit} rows per section. Totals and downloads include all matching records.</p><button className="secondary" onClick={()=>setLimit(n=>n+50)}>Show more records</button></div>}
 </>}
 </>;
}
