'use client';
import {useState,useRef} from 'react';
import {saveWorkspaceRecord} from '@/lib/workspace-save';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {Org,Entry} from '@/lib/model';
import {DeadlineTime,RecordTime} from './record-time';
import DeadlineFields from './deadline-fields';
export default function ObligationDeadline({org,entry,reload,onBusy}:{org:Org;entry:Entry;reload:()=>Promise<void>;onBusy?:(busy:boolean)=>void}){
 const savingNow=useRef(false);
 const [baseline,setBaseline]=useState({version:org.version,deadlineAt:entry.deadline?.at||'',historyCount:entry.deadlineHistory?.length||0});
 const [open,setOpen]=useState(false),[time,setTime]=useState(entry.deadline?.localDateTime.slice(11)||''),[timeZone,setZone]=useState(entry.deadline?.timeZone||'UTC'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();if(savingNow.current)return;savingNow.current=true;setBusy(true);onBusy?.(true);setError('');try{
  await saveWorkspaceRecord({action:'obligationDeadline',orgId:org.id,...baseline,entryId:entry.id,deadlineTime:time,deadlineTimeZone:timeZone,reason});
  setOpen(false);toast.success('Submission deadline recorded');try{await reload();}catch{toast.warning('The deadline was saved, but the workspace could not refresh. Refresh before editing again.');}
 }catch(e){setError((e as Error).message);}finally{savingNow.current=false;setBusy(false);onBusy?.(false);}}
 return <><DeadlineTime entry={entry}/>{org.permissions?.canManage&&<button className="text-button" disabled={busy} onClick={()=>{if(savingNow.current)return;setBaseline({version:org.version,deadlineAt:entry.deadline?.at||'',historyCount:entry.deadlineHistory?.length||0});setTime(entry.deadline?.localDateTime.slice(11)||'');setZone(entry.deadline?.timeZone||'UTC');setReason('');setError('');setOpen(true);}}>{entry.deadline?'Change cutoff':'Set cutoff'}</button>}<Dialog open={open} onOpenChange={value=>{if(!savingNow.current)setOpen(value);}}><DialogContent className="editor"><DialogHeader><DialogTitle>Member submission deadline</DialogTitle><DialogDescription>{org.members.find(m=>m.id===entry.memberId)?.name} · {entry.title} · Due date {entry.date}</DialogDescription></DialogHeader><form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0,display:'grid',gap:15}}><DeadlineFields date={entry.date} time={time} timeZone={timeZone} onChange={(t,z)=>{setTime(t);setZone(z);}}/><label className="field">Reason for recording or changing the cutoff<textarea required minLength={5} maxLength={2000} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="form-note">The change is kept in history. Already submitted payments retain the deadline captured at submission. This does not apply fees or change financial credits.</p>{error&&<div role="alert"><p className="form-error">{error}</p>{error.includes("session has expired")&&<a className="text-button" href="/auth" target="_blank" rel="noreferrer">Sign in in another tab</a>}</div>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save cutoff'}</button></div></fieldset></form>{!!entry.deadlineHistory?.length&&<details><summary>Deadline history</summary>{[...entry.deadlineHistory].reverse().map((change,i)=><div className="review-event" key={i}><RecordTime at={change.at}/><p>{change.actorName} · {change.reason}</p><p>{change.previous?'Previous: '+change.previous.localDateTime+' '+change.previous.timeZone:'No earlier cutoff'} → {change.deadline.localDateTime} {change.deadline.timeZone}</p></div>)}</details>}</DialogContent></Dialog></>;
}
