'use client';
import {useState,useRef} from 'react';
import {Plus,Search,ExternalLink,Lightbulb} from 'lucide-react';
import {type Org,type Entry,money} from '@/lib/model';
import {opportunityStages,opportunityCategories} from '@/lib/founder-hub';
import {saveWorkspaceRecord} from '@/lib/workspace-save';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function OpportunitiesWorkspace({org,entries,reload,onBusy}:{org:Org;entries:Entry[];reload:()=>Promise<void>;onBusy:(busy:boolean)=>void}){
 const savingNow=useRef(false);
 const [draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[category,setCategory]=useState('All'),[stage,setStage]=useState('All'),[query,setQuery]=useState(''),[location,setLocation]=useState(''),[budget,setBudget]=useState('');
 const ideas=entries.filter(e=>e.orgId===org.id&&e.type==='opportunity'),filtered=ideas.filter(e=>(category==='All'||e.opportunity?.category===category)&&(stage==='All'||e.status===stage)&&(!query||`${e.title} ${e.purpose} ${e.opportunity?.location}`.toLowerCase().includes(query.toLowerCase()))&&(!budget||!e.amountMinor||e.amountMinor<=Number(budget)*100));
 const start=(entry?:Entry)=>{setError('');setDraft(entry?{submissionId:entry.id.split(':opportunity:')[1],revision:entry.opportunity?.revision,title:entry.title,description:entry.purpose,amount:entry.amountMinor?String(entry.amountMinor/100):'',category:entry.opportunity?.category||'Other',stage:entry.status,location:entry.opportunity?.location||'',sourceUrl:entry.opportunity?.sourceUrl||'',risks:entry.opportunity?.risks||'',nextStep:entry.opportunity?.nextStep||''}:{submissionId:crypto.randomUUID(),revision:0,title:'',description:'',amount:'',category:'SaaS',stage:'Idea',location:'',sourceUrl:'',risks:'',nextStep:''});};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(savingNow.current)return;savingNow.current=true;setBusy(true);onBusy(true);setError('');try{await saveWorkspaceRecord({...draft,orgId:org.id,action:'saveOpportunity'});setDraft(null);await reload();}catch(e){setError((e as Error).message);}finally{savingNow.current=false;setBusy(false);onBusy(false);}};
 const researchQuery=[category==='All'?'businesses or properties for sale':category==='SaaS'?'SaaS businesses for sale':category==='Real estate'?'investment properties for sale':category==='Business acquisition'?'small businesses for sale':'investment opportunities',location,budget?`under $${budget}`:''].filter(Boolean).join(' ');
 return <div className="opportunities-workspace"><div className="section-intro"><button className="primary" onClick={()=>start()}><Plus size={16}/> Add opportunity</button></div><section className="panel opportunity-filters"><label className="field">Search saved ideas<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, description or location"/></label><label className="field">Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All',...opportunityCategories].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Maximum capital estimate ({org.currency})<input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Any budget"/></label></section>
 <div className="opportunity-stage-strip">{opportunityStages.map(s=><button key={s} aria-pressed={stage===s} onClick={()=>setStage(stage===s?'All':s)}><span>{s}</span><strong>{ideas.filter(e=>e.status===s).length}</strong></button>)}</div>
 <div className="opportunity-grid">{filtered.map(entry=><section className="panel opportunity-card" key={entry.id}><div className="panel-header"><span className="eyebrow">{entry.opportunity?.category}</span><span className={'badge '+(entry.status==='Approved'?'green':entry.status==='Passed'?'neutral':'pending')}>{entry.status}</span></div><div className="hub-panel-body"><h3>{entry.title}</h3><p>{entry.purpose||'No description recorded.'}</p><dl><dt>Capital estimate</dt><dd>{entry.amountMinor?money(entry.amountMinor,entry.currency):'Not established'}</dd><dt>Location</dt><dd>{entry.opportunity?.location||'Not specified'}</dd><dt>Submitted by</dt><dd>{entry.submittedName||'Founder'}</dd></dl><div className="opportunity-risk"><strong>Questions & risks</strong><p>{entry.opportunity?.risks||'Research still needed.'}</p><strong>Next step</strong><p>{entry.opportunity?.nextStep||'Discuss the idea with the founders.'}</p></div><div className="opportunity-actions">{entry.opportunity?.sourceUrl&&<a className="secondary" href={entry.opportunity.sourceUrl} target="_blank" rel="noopener noreferrer">Source <ExternalLink size={14}/></a>}{entry.canEditOpportunity&&<button className="secondary" onClick={()=>start(entry)}>Edit / move stage</button>}</div><details><summary>Review history</summary>{entry.opportunity?.history.map((h,i)=><p key={i}>{h.at.slice(0,10)} · {h.actorName} · {h.stage}</p>)}</details></div></section>)}</div>{!filtered.length&&<section className="panel empty"><Lightbulb size={30}/><h3>{ideas.length?'No ideas match these filters':'Good opportunities start with a question.'}</h3><p>{ideas.length?'Adjust the category, stage or budget. Unknown capital estimates remain visible.':'Add a SaaS concept, property listing or business for the group to investigate.'}</p></section>}
 <section className="panel research-launcher"><div className="panel-header"><div><h2>Start an opportunity search</h2><p className="muted">Open an external search, then save useful sources for review.</p></div><Search size={22}/></div><div className="hub-panel-body"><label className="field">Preferred location<input value={location} onChange={e=>setLocation(e.target.value)} maxLength={180} placeholder="City, state or remote"/></label><a className="secondary" href={'https://www.google.com/search?q='+encodeURIComponent(researchQuery)} target="_blank" rel="noopener noreferrer">Search the web <ExternalLink size={14}/></a><p className="hub-caption">This opens a search; it does not fetch, verify or recommend listings. An automated research agent is a follow-on feature once Mola agrees its search criteria.</p></div></section><p className="hub-caption">Approved means approved for further planning in this register. Spending still requires a separate funding request and its required approvals.</p>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="editor"><DialogHeader><DialogTitle>{draft?.revision?'Review opportunity':'Add opportunity'}</DialogTitle><DialogDescription>All founders can read this idea. Use public sources and shared business information only.</DialogDescription></DialogHeader>{draft&&<form onSubmit={submit}><fieldset disabled={busy} className="founder-form">{[['title','Opportunity name'],['amount',`Capital estimate (${org.currency}, optional)`],['location','Location'],['sourceUrl','Source URL']].map(([key,label])=><label className="field" key={key}>{label}<input required={key==='title'} type={key==='sourceUrl'?'url':'text'} value={draft[key]} maxLength={key==='sourceUrl'?1500:180} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label className="field">Category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{opportunityCategories.map(s=><option key={s}>{s}</option>)}</select></label>{draft.revision>0&&<label className="field">Stage<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value})}>{(org.permissions?.canManage?opportunityStages:['Idea','Researching']).map(s=><option key={s}>{s}</option>)}</select></label>}{[['description','What is the opportunity?',3000],['risks','Questions and risks',2000],['nextStep','Proposed next step',1000]].map(([key,label,max])=><label className="field" key={key}>{label}<textarea rows={3} value={draft[key]} maxLength={Number(max)} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button className="secondary" type="button" onClick={()=>setDraft(null)}>Cancel</button><button className="primary" type="submit">{busy?'Saving…':'Save opportunity'}</button></div></fieldset></form>}</DialogContent></Dialog>
 </div>;
}
