'use client';
import {ArrowDownLeft,ShieldCheck,FileText,HelpCircle,ChevronRight} from 'lucide-react';
import type {Org} from '@/lib/model';
const states=[
 ['Awaiting verification','A member has reported an external payment. A reviewer still needs to check the receiving-account evidence.'],
 ['Owner reconciled','The workspace owner has recorded a provisional reconciliation. It is separate from independent verification.'],
 ['Verified','A different authorized member has checked the receipt evidence. Only an explicitly assigned credit reduces an obligation.'],
 ['Rejected','The report was not accepted. Review the recorded reason before submitting another report. Earlier reviews remain in history.'],
 ['Internally authorized','The funding request has enough eligible approvals for its current version and rule. This does not send money or confirm a bank withdrawal.'],
 ['Payment reported','The owner recorded a payment made outside the app. It includes the receipt reference and the approval snapshot; bank or recipient confirmation is not automated.'],
 ['Voided report','An inaccurate external-payment report was excluded from reported spending. Its history remains. This does not reverse a bank transaction or record a refund.'],
];
export default function PilotGuide({org,disabled,onOpen}:{org:Org;disabled:boolean;onOpen:(view:string)=>void}){
 const open=(view:string)=>{if(!disabled)onOpen(view);};
 return <div className="pilot-guide"><section className="panel guide-intro"><HelpCircle size={25}/><div><h2>Using your Mola workspace</h2><p>Keep the group’s records clear: report contributions, review external evidence, and track approved spending. The app records these steps; payments take place outside it.</p></div></section>
 <div className="guide-workflows"><section className="panel guide-card"><ArrowDownLeft size={23}/><h2>Report your contribution</h2><ol><li>Make the payment using your group’s agreed external payment details.</li><li>Open your unpaid obligation on Overview, or choose Record contribution.</li><li>Enter the amount actually paid, payment date, method and receipt reference. An extra amount is allowed.</li><li>Check any warning about existing pending reports or matching references, then save once.</li></ol><p>Your remaining dues change after a reviewer assigns credit. Extra contributions do not automatically cover future weekly dues or create ownership units.</p><button type="button" className="secondary" disabled={disabled} onClick={()=>open('overview')}>Open my overview <ChevronRight size={16}/></button></section>
 <section className="panel guide-card"><ShieldCheck size={23}/><h2>Review a receipt</h2><ol><li>Open Contributions and use the receipt review queue.</li><li>Compare the member’s report with the receiving-account receipt or statement.</li><li>Check similar references, choose an outcome and record your evidence.</li><li>If appropriate, assign credit to the matching member’s obligation in the same currency. Check the balance preview before saving.</li></ol><p>Contributors and submitters cannot independently verify their own payment. Corrections replace the previous credit and preserve review history.</p><button type="button" className="secondary" disabled={disabled} onClick={()=>open('contributions')}>Open contributions <ChevronRight size={16}/></button></section>
 <section className="panel guide-card"><FileText size={23}/><h2>Track an investment payment</h2><ol><li>Draft a funding request with the amount, recipient reference and purpose.</li><li>Collect the required distinct approvals. The requester cannot self-approve.</li><li>After a payment is made outside the app, the owner records its amount, fees, sender and receipt reference.</li><li>Use the group treasury statement to review spending and export the complete records.</li></ol><p>Changing request terms restarts approvals. Active payment reports lock revisions. Payment amounts and fees together must stay within the authorization.</p><button type="button" className="secondary" disabled={disabled} onClick={()=>open('requests')}>Open funding requests <ChevronRight size={16}/></button></section></div>
 <section className="panel guide-statuses"><div className="panel-header"><h2>What each status means</h2></div><dl>{states.map(([label,meaning])=><div key={label}><dt>{label}</dt><dd>{meaning}</dd></div>)}</dl></section>
 <section className="panel guide-questions"><div className="panel-header"><h2>Common questions</h2></div><details><summary>I paid, but my dues still show a balance. Why?</summary><p>A pending report does not reduce dues. A reviewer must check receipt and explicitly assign credit to the obligation. A verified payment can remain unallocated. Open your statement to see both the payment status and the assigned credits.</p></details><details><summary>Can I pay more than the weekly minimum?</summary><p>Yes. Record the amount actually paid. The excess does not automatically satisfy future obligations. Ownership units and voting power depend on the group’s adopted policies, not on a displayed contribution total alone.</p></details><details><summary>A save failed or the connection dropped. Should I try again?</summary><p>Keep the form open and read its message. An uncertain save may already have reached the server. Check the register or refresh the workspace before creating a new report. Retrying the same contribution or external-payment report preserves its submission identity; starting a new report does not.</p></details><details><summary>Does the group statement show money available in the bank?</summary><p>No. It compares the records currently in the app. It does not include an opening bank balance, unrecorded transfers or current investment values. Pending and provisional contributions stay separate, and external payments are owner reports. Reconcile against the bank statement before relying on available funds.</p></details><details><summary>Why did a funding request lose its approvals?</summary><p>A changed amount, recipient, purpose, request version or approval rule can require fresh approvals. Changes to an approver’s active account can also affect whether their vote counts. The request shows the current eligible approval count and earlier versions remain in history.</p></details><details><summary>How do I correct a mistake?</summary><p>For a contribution, ask an authorized reviewer to record a correction with its reason. For an inaccurate external-payment report, the owner can void the report while preserving the original. A reporting correction never reverses money at the bank.</p></details></section>
 {org.permissions?.isOwner&&<section className="panel guide-owner"><div><h2>Preparing the group?</h2><p>Pilot setup brings together your founder link, member and reviewer accounts, weekly dues, collection-account labels, agreement and funding approvers. Use the group’s actual decisions and details.</p></div><button type="button" className="primary" disabled={disabled} onClick={()=>open('pilotsetup')}>Open pilot setup</button></section>}
 </div>;
}
