'use client';
import {useState} from 'react';
import {type Entry,type Org,money} from '@/lib/model';
import {receiptQueue,type ReceiptQueueFilter} from '@/lib/receipt-queue';
import {RecordTime} from './record-time';
export default function ReceiptQueue({org,entries,disabled,onReview,onOpen}:{org:Org;entries:Entry[];disabled:boolean;onReview:(entry:Entry)=>void;onOpen:(entry:Entry)=>void}){
 const [filter,setFilter]=useState<ReceiptQueueFilter>('pending'),[limit,setLimit]=useState(5);
 if(org.mode!=='Shared ownership')return null;
 const queue=receiptQueue(org,entries,filter);
 const choose=(next:ReceiptQueueFilter)=>{setFilter(next);setLimit(5);};
 return <section className="panel receipt-queue" aria-labelledby="receipt-queue-title"><div className="panel-header"><div><h2 id="receipt-queue-title">Receipt review queue</h2><p className="muted">Check each report against the receiving bank account. A screenshot is supporting evidence, not confirmation that funds arrived.</p></div><span className={'badge '+(queue.pending?'pending':'neutral')}>{queue.pending?`${queue.pending} awaiting verification`:'No pending reviews'}</span></div>
 <div className="receipt-queue-filters" role="group" aria-label="Receipt queue filters">{([['actionable',`For your review (${queue.actionable})`],['pending',`All pending (${queue.pending})`],['provisional',`Owner reconciled (${queue.provisional})`]] as const).map(([value,label])=><button key={value} type="button" className="secondary" aria-pressed={filter===value} onClick={()=>choose(value)}>{label}</button>)}</div>
 <p className="receipt-queue-caption">{filter==='provisional'?'These payments have provisional owner reconciliation. An eligible different member must review the evidence before independent verification.':`${queue.independent} pending ${queue.independent===1?'payment is':'payments are'} eligible for your independent review. Contributor and submitter restrictions still apply.`} Oldest recorded submission first.</p>
 {queue.totals.length>0&&<div className="receipt-queue-caption" aria-label="Reported amounts in selected queue"><strong>{filter==='provisional'?'Provisional reported amounts':'Reported amounts awaiting review'}</strong><ul>{queue.totals.map(total=><li key={total.currency}>{total.amountMinor===null?'Total exceeds display limit':money(total.amountMinor,total.currency)} {total.currency} · {total.count} {total.count===1?'payment':'payments'}</li>)}</ul><small>Includes all payments in this filter, not just the visible rows. These are reported amounts, not a confirmed bank balance. No currency conversion is applied.</small></div>}
 {queue.rows.length?<div className="receipt-queue-list">{queue.rows.slice(0,limit).map(entry=><article className="receipt-queue-row" key={entry.id}><div className="receipt-queue-person"><h3>{org.members.find(m=>m.id===entry.memberId)?.name||'Member'}</h3><p>{entry.title}</p><small>Recorded <RecordTime at={entry.created}/></small><small>Payment method: {entry.method||'Not specified'}</small><small>Receipt reference: {entry.reference||'Not supplied'}</small><small>{entry.hasReceipt?'Screenshot attached · private':'Screenshot required before review'}</small></div><div className="receipt-queue-amount"><strong>{money(entry.amountMinor,entry.currency)} {entry.currency}</strong><span className={'badge '+(entry.status==='Awaiting verification'?'pending':'neutral')}>{entry.status}</span></div><div className="receipt-queue-actions">{(entry.canReview||entry.canOwnerReconcile)?<button className="primary" type="button" disabled={disabled} onClick={()=>{if(!disabled)onReview(entry);}}>{entry.canReview?'Review receipt':'Reconcile provisionally'}</button>:<p className="muted">A different authorized reviewer is needed.</p>}<button className="secondary" type="button" disabled={disabled} onClick={()=>{if(!disabled)onOpen(entry);}}>{entry.hasReceipt&&entry.canViewReceipt?'View screenshot & details':entry.canUploadReceipt?'Add screenshot / details':'Open details'}</button></div></article>)}</div>:<div className="empty compact"><h3>{filter==='actionable'?'No receipts waiting for your review':filter==='provisional'?'No provisional reconciliations':'No pending payment reports'}</h3><p>{filter==='actionable'&&queue.pending?'Other pending payments need a different authorized reviewer.':'New records and review changes appear after the workspace refreshes.'}</p></div>}
 {queue.rows.length>limit&&<div className="register-more"><button type="button" className="secondary" onClick={()=>setLimit(n=>n+10)}>Show more ({queue.rows.length-limit} remaining)</button></div>}
 </section>;
}
