'use client';
import {useRef,useState} from 'react';
import type {Entry} from '@/lib/model';
import {uploadReceipt} from '@/lib/receipt-upload';
import {receiptUrl} from '@/lib/receipt-url';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function ReceiptAttachment({entry,onSaved,onBusy,initialFile=null,initialError=''}:{initialFile?:File|null;initialError?:string;entry:Entry;onSaved?:(e:Entry)=>void;onBusy?:(busy:boolean)=>void}){
 const [file,setFile]=useState<File|null>(initialFile),[busy,setBusy]=useState(false),[error,setError]=useState(initialError),[preview,setPreview]=useState(false);const latch=useRef(false);
 async function upload(){if(!file||latch.current)return;latch.current=true;setBusy(true);onBusy?.(true);setError('');try{const updated=await uploadReceipt(entry,file);setFile(null);onSaved?.(updated);}catch(e){setError((e as Error).message);}finally{latch.current=false;setBusy(false);onBusy?.(false);}}
 return <section className="receipt-attachment"><h3>Private payment screenshot</h3><p>The screenshot is required evidence for this report. A reviewer must still check the deposit in Mola’s receiving account.</p>{entry.canViewReceipt?<button type="button" className="secondary" onClick={()=>setPreview(true)}>View attached screenshot</button>:entry.hasReceipt?<p>Attachment visible only to the contributor, owner and designated reviewers.</p>:<p>No screenshot attached. This payment has not been submitted for review.</p>}{entry.canUploadReceipt&&onSaved&&<><label className="field">Required screenshot · PNG or JPEG, up to 3 MB<input type="file" required accept="image/png,image/jpeg" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setError('');}}/></label><p>Crop out balances, full account numbers and unrelated transactions before uploading. One attachment per report; it cannot be replaced after upload.</p>{file&&<p>Selected: {file.name}</p>}<button type="button" className="secondary" disabled={!file||busy} onClick={upload}>{busy?'Uploading…':'Attach screenshot and submit'}</button></>}{error&&<p className="form-error" role="alert">{error}</p>}<Dialog open={preview} onOpenChange={setPreview}><DialogContent className="receipt-preview"><DialogHeader><DialogTitle>Payment screenshot</DialogTitle><DialogDescription>Private evidence for {entry.title}. Close this preview to return to the payment record.</DialogDescription></DialogHeader>{preview&&<div className="receipt-preview-canvas"><img src={receiptUrl(entry.orgId,entry.id)} alt={`Payment screenshot for ${entry.title}`}/></div>}</DialogContent></Dialog></section>;
}
