'use client';
import {useState,useRef} from 'react';
import {Plus,Target,Landmark} from 'lucide-react';
import {type Org,type Entry,money} from '@/lib/model';
import {type SavingsGoal,goalProgress} from '@/lib/founder-hub';
import SavingsCalculator from './savings-calculator';
import {saveWorkspaceRecord} from '@/lib/workspace-save';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function SavingsWorkspace({org,entries,reload,onBusy}:{org:Org;entries:Entry[];reload:()=>Promise<void>;onBusy:(busy:boolean)=>void}){
 const savingNow=useRef(false);
 const today=new Date().toISOString().slice(0,10),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const start=(goal?:SavingsGoal)=>{setError('');setDraft(goal?{action:'saveSavingsGoal',goalId:goal.id,title:goal.title,amount:String(goal.targetMinor/100),startDate:goal.startDate,targetDate:goal.targetDate,status:goal.status,description:goal.description}:{action:'saveSavingsGoal',goalId:crypto.randomUUID(),title:'Mola Capital Fund',amount:'1000000',startDate:today,targetDate:`${Number(today.slice(0,4))+5}${today.slice(4)}`,status:'Planning',description:''});};
 const input=(key:string,label:string,type='text',required=true)=><label className="field">{label}<input type={type} required={required} value={draft[key]} maxLength={key==='amount'?30:180} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>;
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(savingNow.current)return;savingNow.current=true;setBusy(true);onBusy(true);setError('');try{await saveWorkspaceRecord({...draft,orgId:org.id,version:org.version});setDraft(null);await reload();}catch(e){setError((e as Error).message);}finally{savingNow.current=false;setBusy(false);onBusy(false);}};
 return <div className="savings-workspace"><div className="section-intro">{org.permissions?.canManage&&<button className="primary" onClick={()=>start()}><Plus size={16}/> Add savings goal</button>}</div>
  <div className="goal-grid">{(org.savingsGoals||[]).filter(g=>g.status!=='Archived').map(goal=>{const p=goalProgress(goal,entries,org.id);return <section className="panel goal-card" key={goal.id}><div className="panel-header"><h3>{goal.title}</h3><span className={'badge '+(goal.status==='Active'?'green':'neutral')}>{goal.status}</span></div><div className="hub-panel-body"><div className="goal-big-number">{money(p.verified,goal.currency)}<small> of {money(goal.targetMinor,goal.currency)}</small></div><progress value={p.percent} max="100" aria-label={goal.title+' progress'}/><div className="goal-meta"><span>{p.percent.toFixed(1)}% contributed</span><span>Target {goal.targetDate}</span></div><p>{goal.description||'A shared contribution target for the founding group.'}</p><small>Contributions from {goal.startDate} · {money(p.remaining,goal.currency)} remaining.</small>{org.permissions?.canManage&&<button className="text-button" onClick={()=>start(goal)}>Edit goal</button>}<details><summary>Goal change history</summary>{goal.history.map((h,i)=><p key={i}>{h.at.slice(0,10)} · {h.actorName} · {h.summary}</p>)}</details></div></section>;})}{!(org.savingsGoals||[]).some(g=>g.status!=='Archived')&&<section className="panel empty"><Target size={30}/><h3>No shared goal yet</h3><p>Start with a capital fund while you explore where Mola will invest.</p></section>}</div>
  {(org.savingsGoals||[]).some(g=>g.status==='Archived')&&<details className="panel hub-panel-body"><summary>Archived savings goals</summary>{org.savingsGoals!.filter(g=>g.status==='Archived').map(g=><p key={g.id}>{g.title} · {money(g.targetMinor,g.currency)} {org.permissions?.canManage&&<button className="text-button" onClick={()=>start(g)}>Edit / restore</button>}</p>)}</details>}
  <SavingsCalculator org={org} entries={entries}/>
  <section className="panel"><div className="panel-header"><div><h2>Bank balance checkpoints</h2><p className="muted">Dated balances recorded after a human bank check.</p></div><Landmark size={22}/></div><div className="hub-panel-body">{org.permissions?.canManage&&<button className="secondary" onClick={()=>{setError('');setDraft({action:'saveCashCheckpoint',amount:'',asOf:today,accountLabel:org.accountLabel||'',note:'',bankChecked:false});}}>Record a checked balance</button>}{org.cashCheckpoints?.length?<div className="checkpoint-list">{[...org.cashCheckpoints].reverse().slice(0,10).map((c,i)=><div key={i}><strong>{money(c.amountMinor,c.currency)}</strong><span>As of {c.asOf} · {c.accountLabel}</span><small>Recorded by {c.recordedName} · {c.note}</small></div>)}</div>:<p>No balance has been recorded. Verified contributions alone do not establish bank cash.</p>}<p className="hub-caption">Historical human reports; no bank connection. Checkpoints do not create contributions, ownership units or spendable approvals.</p></div></section>
  <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="editor"><DialogHeader><DialogTitle>{draft?.action==='saveCashCheckpoint'?'Record bank balance checkpoint':'Shared savings goal'}</DialogTitle><DialogDescription>{draft?.action==='saveCashCheckpoint'?'Use a masked account label and evidence reference only. Do not include account numbers or private transactions.':'Goal changes are shared with all founders. They do not change weekly dues or reserve cash.'}</DialogDescription></DialogHeader>{draft&&<form onSubmit={submit}><fieldset disabled={busy} className="founder-form">{draft.action==='saveCashCheckpoint'?<>{input('amount',`Checked balance (${org.currency})`)}{input('asOf','Balance date','date')}{input('accountLabel','Account label (no full number)')}<label className="field">Shared evidence note<textarea required minLength={5} maxLength={1000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><label className="check-field"><input type="checkbox" required checked={draft.bankChecked} onChange={e=>setDraft({...draft,bankChecked:e.target.checked})}/>I checked this balance against the bank or bank statement.</label></>:<>{input('title','Goal name')}{input('amount',`Contribution target (${org.currency})`)}{input('startDate','Count contributions from','date')}{input('targetDate','Target date','date')}<label className="field">Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{['Planning','Active','Archived'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Shared purpose<textarea maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button className="secondary" type="button" onClick={()=>setDraft(null)}>Cancel</button><button className="primary" type="submit">{busy?'Saving…':'Save'}</button></div></fieldset></form>}</DialogContent></Dialog>
 </div>;
}
