'use client';
import {useState} from 'react';
import {Calculator,ChevronDown} from 'lucide-react';
import {type Org,type Entry,money,weeklyMinimum} from '@/lib/model';
import {calendarScenario,verifiedInPeriod,type ScenarioInput} from '@/lib/savings-scenario';
const formatDate=(value:string)=>new Date(value+'T00:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
const monthName=(value:string)=>new Date(value+'-01T00:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'});
export default function SavingsCalculator({org,entries}:{org:Org;entries:Entry[]}){
 const unit=org.currency==='XAF'?1:100,today=new Date().toISOString().slice(0,10);
 const [scenario,setScenario]=useState({startDate:org.weeklySchedule?.startDate||today,weekly:String(weeklyMinimum(org)/unit),founders:org.members.length,years:5,months:0,growth:100,growthTiming:'calendar' as ScenarioInput['growthTiming'],collection:100,opening:'0',spending:'0'}),[view,setView]=useState<'group'|'founder'>('group');
 let plan:ReturnType<typeof calendarScenario>|null=null,error='';
 try{const minor=(s:string)=>{if(!(unit===1?/^\d+$/:/^\d+(\.\d{1,2})?$/).test(s))throw new Error(unit===1?'Use whole non-negative XAF amounts.':'Use non-negative amounts with at most two decimal places.');return Math.round(Number(s)*unit);};plan=calendarScenario({startDate:scenario.startDate,years:scenario.years,months:scenario.months,weeklyMinor:minor(scenario.weekly),founders:scenario.founders,growthPercent:scenario.growth,growthTiming:scenario.growthTiming,collectionPercent:scenario.collection,openingMinor:minor(scenario.opening),annualSpendingMinor:minor(scenario.spending)});}catch(e){error=(e as Error).message;}
 const amount=(n:number)=>money(n,org.currency),rateRange=(low:number,high:number,multiplier=1)=>low===high?amount(low*multiplier):`${amount(low*multiplier)} → ${amount(high*multiplier)}`;
 const numeric=(key:'founders'|'years'|'months'|'growth'|'collection',label:string,min:number,max:number)=><label className="field">{label}<input type="number" min={min} max={max} step={key==='growth'||key==='collection'?0.1:1} value={Number.isNaN(scenario[key])?'':scenario[key]} onChange={e=>setScenario({...scenario,[key]:e.target.value===''?NaN:Number(e.target.value)})}/></label>;
 return <section className="panel calendar-planner"><div className="panel-header"><div><span className="eyebrow">YOUR CONTRIBUTION SCENARIO</span><h2>Plan from the day you start.</h2><p className="muted">Full years, partial years, and the weekly steps in between.</p></div><Calculator size={22}/></div>
 <div className="calendar-planner-layout"><div className="calendar-controls">
 <label className="field">First weekly payment date<input type="date" value={scenario.startDate} onChange={e=>setScenario({...scenario,startDate:e.target.value})}/></label><label className="field">Starting weekly amount per founder ({org.currency})<input inputMode="decimal" value={scenario.weekly} onChange={e=>setScenario({...scenario,weekly:e.target.value})}/></label>
 <div className="duration-fields">{numeric('years','Years',0,10)}{numeric('months','Extra months',0,11)}</div><div className="scenario-presets" role="group" aria-label="Plan duration presets">{[3,5,6].map(years=><button type="button" key={years} aria-pressed={scenario.years===years&&scenario.months===0} onClick={()=>setScenario({...scenario,years,months:0})}>{years} years</button>)}</div>
 {numeric('founders','Number of founders',1,100)}{numeric('growth','Annual increase (%)',0,100)}<label className="field">Apply annual increase<select value={scenario.growthTiming} onChange={e=>setScenario({...scenario,growthTiming:e.target.value as ScenarioInput['growthTiming']})}><option value="calendar">Every January 1</option><option value="anniversary">On the start-date anniversary</option></select></label>
 <details className="scenario-assumptions"><summary>Collection, opening capital & spending</summary>{numeric('collection','Expected collection (%)',0,100)}<label className="field">Starting group capital ({org.currency})<input inputMode="decimal" value={scenario.opening} onChange={e=>setScenario({...scenario,opening:e.target.value})}/></label><label className="field">Annual group spending ({org.currency})<input inputMode="decimal" value={scenario.spending} onChange={e=>setScenario({...scenario,spending:e.target.value})}/></label></details>
 <p className="hub-caption">A weekly payment is counted on the start date, then every 7 days. Calendar years can contain 52 or 53 payments; partial years count only covered dates. Spending is prorated by calendar days. No investment returns, loans or taxes are assumed.</p><p className="hub-caption">This scenario is not saved. It does not adopt rates, generate dues or change company records.</p>
 </div><div className="calendar-output" aria-live="polite">{error?<p className="form-error" role="alert">{error}</p>:plan&&<>
 <div className="forecast-total"><span>PROJECTED GROUP CAPITAL AFTER {scenario.years?`${scenario.years} YEAR${scenario.years===1?'':'S'}`:''}{scenario.months?`${scenario.years?' + ':''}${scenario.months} MONTH${scenario.months===1?'':'S'}`:''}</span><strong>{amount(plan.cumulative)}</strong><small>{formatDate(plan.startDate)} – {formatDate(plan.through)} · {plan.totalWeeks} weekly payments per founder</small></div>
 <div className="scenario-overview"><div><span>Starting weekly · founder</span><strong>{amount(Number(scenario.weekly)*unit)}</strong></div><div><span>Starting weekly · group</span><strong>{amount(Number(scenario.weekly)*unit*scenario.founders)}</strong></div><div><span>Expected collected · group</span><strong>{amount(plan.collected)}</strong></div></div>
 <div className="scenario-table-heading"><h3>Every calendar year</h3><div role="group" aria-label="Projection breakdown"><button type="button" aria-pressed={view==='group'} onClick={()=>setView('group')}>Group</button><button type="button" aria-pressed={view==='founder'} onClick={()=>setView('founder')}>Per founder</button></div></div>
 <div className="table-wrap"><table className="calendar-year-table"><caption className="sr-only">{view==='group'?'Group projections by calendar year':'Equal contribution projections per founder by calendar year'}</caption><thead><tr><th scope="col">Year / covered dates</th><th scope="col">Weeks</th><th scope="col">Weekly {view==='group'?'group':'per founder'}</th><th scope="col">Monthly average</th><th scope="col">Year contribution</th><th scope="col">Expected collected</th>{view==='group'&&<><th scope="col">Spending</th><th scope="col">Capital at period end</th></>}</tr></thead><tbody>{plan.years.map(r=><tr key={r.year}><th scope="row"><strong>{r.year}</strong>{r.partial&&<span className="badge neutral">Partial year</span>}<small>{formatDate(r.from)} – {formatDate(r.through)}</small></th><td>{r.weeks}</td><td>{r.weeks?rateRange(r.weeklyLow,r.weeklyHigh,view==='group'?scenario.founders:1):'No payment dates'}</td><td>{amount(view==='group'?r.monthlyAverage:r.monthlyAveragePerFounder)}</td><td>{amount(view==='group'?r.planned:r.plannedPerFounder)}</td><td>{amount(view==='group'?r.collected:r.collectedPerFounder)}</td>{view==='group'&&<><td>{amount(r.spending)}</td><td><strong>{amount(r.cumulative)}</strong></td></>}</tr>)}</tbody></table></div>
 <p className="hub-caption">Monthly averages use only the calendar months covered in that row, including partial months. Open a year below for exact monthly totals and weekly payment dates. {scenario.growthTiming==='calendar'?'Rates increase each January 1, including after a partial first year.':'Rates increase on each start-date anniversary; a calendar year may span two rates.'}</p>
 <div className="scenario-year-details"><h3>Month by month & founder records</h3>{plan.years.map(r=><details key={r.year} className="scenario-year-detail"><summary><span>{r.year} · {r.weeks} weekly payments{r.partial?' · partial year':''}</span><ChevronDown size={16}/></summary><div className="table-wrap"><table><thead><tr><th scope="col">Month</th><th scope="col">Weeks</th><th scope="col">Per founder</th><th scope="col">Group contribution</th><th scope="col">Expected collected</th><th scope="col">Verified records</th><th scope="col">Projected capital</th></tr></thead><tbody>{r.months.map(m=><tr key={m.month}><th scope="row">{monthName(m.month)}<small>{m.from} – {m.through}</small><details className="payment-dates"><summary>Weekly dates</summary><span>{m.paymentDates.join(' · ')||'No scheduled payment in this interval'}</span></details></th><td>{m.weeks}</td><td>{amount(m.plannedPerFounder)}</td><td>{amount(m.planned)}</td><td>{amount(m.collected)}</td><td>{amount(verifiedInPeriod(org,entries,m.from,m.through,undefined,today))}</td><td>{amount(m.cumulative)}</td></tr>)}</tbody></table></div>
 <div className="founder-period-records"><h4>Current founders · verified in this period</h4><p className="hub-caption">Current status of payments dated {r.from} – {r.through}, checked through {today}. These actual records are separate from the projection. Pending and provisional contributions are excluded.</p><div className="table-wrap"><table><thead><tr><th scope="col">Founder</th><th scope="col">Scenario weekly rate</th><th scope="col">Scenario year contribution</th><th scope="col">Actual verified</th></tr></thead><tbody>{org.members.map(member=><tr key={member.id}><th scope="row">{member.name}</th><td>{r.weeks?rateRange(r.weeklyLow,r.weeklyHigh):'No payment dates'}</td><td>{amount(r.plannedPerFounder)}</td><td>{amount(verifiedInPeriod(org,entries,r.from,r.through,member.id,today))}</td></tr>)}</tbody></table></div>{scenario.founders!==org.members.length&&<p className="hub-caption">The scenario uses {scenario.founders} founders. Actual records above belong to the current {org.members.length} members.</p>}</div></details>)}</div>
 </>}</div></div></section>;
}
