'use client';
import {Org,Entry,money,obligationStanding} from '@/lib/model';
import ObligationDeadline from './obligation-deadline';
import {RecordTime} from './record-time';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
export default function Standing({org,entries,onAdd,reload,onBusy}:{org:Org;entries:Entry[];onAdd:()=>void;reload:()=>Promise<void>;onBusy?:(busy:boolean)=>void}){
const dues=entries.filter(e=>e.type==='obligation'),payments=entries.filter(e=>e.type==='contribution'),currencies=['USD','CAD','XAF'].filter(c=>dues.some(e=>e.currency===c));
const invalidCredits=dues.reduce((total,due)=>total+obligationStanding(due,entries).ignoredCreditCount,0); return <section className="panel standing"><div className="panel-header"><div><h2>Obligations & remaining balances</h2><p className="muted">Balances include explicitly assigned verified and provisional owner credits.</p></div><button className="secondary" disabled={!org.permissions?.canManage} onClick={onAdd}>Add obligation</button></div><div className="notice"><p>Record agreed dues or individual contract allocations with their dates. Do not enter a full contract obligation and overlapping monthly instalments: that would count the same debt twice. Extra contributions do not automatically cover future dues. Owner reconciliation is not independent verification.</p></div>
{invalidCredits>0&&<div className="notice" role="alert"><p>{invalidCredits} credit assignment(s) need review and were excluded from balances. Check the member, currency, organization, amount and latest review before relying on these totals.</p></div>}{currencies.length>0&&<div className="standing-totals">{currencies.map(c=>{const rows=dues.filter(e=>e.currency===c);const sum=(key:'credit'|'remaining'|'excess')=>rows.reduce((s,e)=>s+obligationStanding(e,entries)[key],0);return <div key={c}><strong>{c} · recorded obligations</strong><p>Due: {money(rows.reduce((s,e)=>s+e.amountMinor,0),c)}</p><p>Credited: {money(sum('credit'),c)}</p><p>Remaining: {money(sum('remaining'),c)}</p>{sum('excess')>0&&<p>Excess assigned credit: {money(sum('excess'),c)}</p>}</div>})}</div>}
<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Member</TableHead><TableHead>Verified / owner-reconciled payments</TableHead><TableHead>Remaining recorded obligations</TableHead><TableHead>Standing</TableHead></TableRow></TableHeader><TableBody>{org.members.map(m=>{const rows=dues.filter(e=>e.memberId===m.id);const ps=payments.filter(e=>e.memberId===m.id&&['Owner reconciled','Verified'].includes(e.status));const late=rows.filter(e=>obligationStanding(e,entries).status==='Behind').length;return <TableRow key={m.id}><TableCell>{m.name}</TableCell><TableCell>{['USD','CAD','XAF'].filter(c=>ps.some(e=>e.currency===c)).map(c=><div key={c}><strong>Verified: {money(ps.filter(e=>e.currency===c&&e.status==='Verified').reduce((s,e)=>s+e.amountMinor,0),c)} {c}</strong><small>Owner: {money(ps.filter(e=>e.currency===c&&e.status==='Owner reconciled').reduce((s,e)=>s+e.amountMinor,0),c)} {c}</small></div>)}{!ps.length?'None reconciled':null}</TableCell><TableCell>{currencies.filter(c=>rows.some(e=>e.currency===c)).map(c=><div key={c}>{money(rows.filter(e=>e.currency===c).reduce((s,e)=>s+obligationStanding(e,entries).remaining,0),c)} {c}</div>)}{!rows.length?'Not configured':null}</TableCell><TableCell><span className={'badge '+(late?'danger':'neutral')}>{late?`${late} overdue`:rows.length?'No overdue recorded dues':'No dues recorded'}</span></TableCell></TableRow>})}</TableBody></Table></div>
{dues.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Obligation / member</TableHead><TableHead>Due date / submission cutoff</TableHead><TableHead>Recorded at (UTC)</TableHead><TableHead>Amount</TableHead><TableHead>Credit / remaining</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{[...dues].sort((a,b)=>a.date.localeCompare(b.date)).map(e=>{const s=obligationStanding(e,entries);return <TableRow key={e.id}><TableCell><strong>{e.title}</strong><small>{org.members.find(m=>m.id===e.memberId)?.name}</small><small>{e.reference||'No agreement reference'}</small></TableCell><TableCell>{e.date}<ObligationDeadline org={org} entry={e} reload={reload} onBusy={onBusy}/></TableCell><TableCell><RecordTime at={e.created}/></TableCell><TableCell>{money(e.amountMinor,e.currency)} {e.currency}</TableCell><TableCell className={s.status==='Behind'?'overdue-amount':undefined}>{money(s.credit,e.currency)} / {money(s.remaining,e.currency)}{s.excess>0&&<small>Excess credit {money(s.excess,e.currency)}</small>}</TableCell><TableCell><span className={'badge '+(s.status==='Covered'?'green':s.status==='Behind'?'danger':'pending')}>{s.status}</span></TableCell></TableRow>})}</TableBody></Table></div>:<div className="empty compact"><h3>No obligations recorded</h3><p>Add a confirmed amount and due date for a member to begin tracking their balance.</p></div>}
</section>;
}
