'use client';
import {useState} from 'react';
import {testRoles} from '@/lib/test-workspace-options';
export type TestContext={session:string;role:string};
export default function TestWorkspaceControls({context,disabled=false}:{context:TestContext;disabled?:boolean}){
 const [deleting,setDeleting]=useState(false),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const navigate=(role:string)=>{if(disabled||busy)return;if(!window.confirm('Switch test member? Any unsaved form will be discarded.'))return;window.location.assign(`/test?${new URLSearchParams({session:context.session,role})}`);};
 async function remove(){if(busy||disabled||confirmation!=='DELETE TEST WORKSPACE')return;setBusy(true);setError('');try{
  const r=await fetch('/api/test-workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',session:context.session,confirmation})});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'Deletion was not confirmed.');window.location.assign('/test');
 }catch(e){setError((e as Error).message);setBusy(false);}}
 return <section className="test-workspace-banner" aria-label="Test environment controls"><div><strong>TEST ENVIRONMENT · Fictional records only</strong><p>These records are separate from Mola. No money moves, emails or invitations are sent. This does not test real sign-in.</p></div><div className="test-workspace-controls"><label>View as test member<select value={context.role} disabled={disabled||busy} onChange={e=>navigate(e.target.value)}>{testRoles.map(r=><option key={r.id} value={r.id}>{r.name} — {r.label}</option>)}</select></label><button className="secondary" disabled={disabled||busy} onClick={()=>{if(window.confirm('Return to your real workspace? Any unsaved form will be discarded.'))window.location.assign('/');}}>Return to real workspace</button><button className="secondary" disabled={disabled||busy} onClick={()=>{setDeleting(!deleting);setError('');setConfirmation('');}}>Delete test workspace</button></div>{deleting&&<div className="test-delete"><p>Delete all fictional members, setup, payments, agreements, approvals and activity in this test workspace? Real Mola and Cameroon records stay unchanged. You can create a fresh test workspace afterward.</p><label className="field">Type DELETE TEST WORKSPACE<input value={confirmation} disabled={busy} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button className="secondary" disabled={busy||disabled||confirmation!=='DELETE TEST WORKSPACE'} onClick={remove}>{busy?'Deleting…':'Permanently delete test records'}</button></div>}{error&&<p role="alert">{error}</p>}<details><summary>Suggested test sequence</summary><ol><li>As Alex, set weekly dues and generate a week of obligations in Pilot setup.</li><li>As Blair, report a fictional payment against your due. Check the pending balance.</li><li>As Casey, review Blair’s receipt and assign its credit. Return as Blair to check the balance.</li><li>As Blair, draft a funding request. Approve it as Casey and Drew; two approvals authorize this test request.</li><li>As Alex, try agreement publishing and external payment reporting using fictional details only.</li></ol><p>The initial test rule requires two approvals. Alex, Casey and Drew are designated approvers. A requester cannot approve their own request. All four names and permissions are fictional.</p></details></section>;
}
