'use client';
import {useState} from 'react';
import {Download} from 'lucide-react';
import {type Org,type Entry,money} from '@/lib/model';
import {treasuryStatement,treasuryCsv,type TreasuryStatement} from '@/lib/treasury-statement';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
export default function TreasuryStatementPanel({org,entries,onOpen}:{org:Org;entries:Entry[];onOpen:(entry:Entry)=>void}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[limit,setLimit]=useState(50),[downloadError,setDownloadError]=useState('');
 let report:TreasuryStatement|undefined,error='';try{report=treasuryStatement(org,entries,from,to);}catch(e){error=(e as Error).message;}
 const reset=()=>{setFrom('');setTo('');setLimit(50);};
 const download=()=>{if(!report)return;setDownloadError('');let url='';try{url=URL.createObjectURL(new Blob([treasuryCsv(org,report)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='mola-group-statement-'+(from||'all')+'-'+(to||'current')+'.csv';document.body.appendChild(a);a.click();a.remove();}catch{setDownloadError('The CSV could not be downloaded. Please try again.');}finally{if(url)setTimeout(()=>URL.revokeObjectURL(url),1000);}};
 return <div className="treasury-statement"><section className="panel statement-controls"><div className="panel-header"><div><h2>Group treasury statement</h2><p className="muted">Contributions, reported spending and recorded dues for {org.name}.</p></div><button className="secondary" type="button" disabled={!report} onClick={download}><Download size={17}/>Download group CSV</button></div><div className="statement-filters"><label className="field">Payment / due date from<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setLimit(50);}}/></label><label className="field">Payment / due date to<input type="date" value={to} onChange={e=>{setTo(e.target.value);setLimit(50);}}/></label><button type="button" className="secondary" disabled={!from&&!to} onClick={reset}>All dates</button></div>{(error||downloadError)&&<p className="form-error statement-error" role="alert">{error||downloadError}</p>}</section>
 <div className="notice"><p>Current loaded statuses, not a historical closing balance. Dates select contribution payments, reported external payments and obligation due dates. Credits from any payment date reduce selected dues. Currencies stay separate.</p></div>
 {report&&<>{report.summaries.length?report.summaries.map(s=><section className="panel treasury-summary" key={s.currency}><div className="panel-header"><h2>{s.currency} · group records</h2><span className="badge neutral">{from||'All earlier dates'} → {to||'Latest date'}</span></div><div className="treasury-columns"><section><h3>Contributions</h3><dl><dt>Independently verified</dt><dd>{money(s.verified,s.currency)}</dd><dt>Awaiting verification</dt><dd>{money(s.pending,s.currency)}</dd><dt>Owner reconciled · provisional</dt><dd>{money(s.owner,s.currency)}</dd><dt>Rejected</dt><dd className={s.rejected>0?'overdue-amount':undefined}>{money(s.rejected,s.currency)}</dd></dl></section><section><h3>External payment reports</h3><dl><dt>Paid to recipients · reported</dt><dd>{money(s.principal,s.currency)}</dd><dt>Reported fees</dt><dd>{money(s.fees,s.currency)}</dd><dt>Total reported spending</dt><dd>{money(s.reportedSpending,s.currency)}</dd></dl><p>Owner reports; not independent bank or recipient confirmation. Voided reports are excluded.</p></section><section><h3>Recorded obligations</h3>{s.dueCount?<dl><dt>Agreed dues</dt><dd>{money(s.due,s.currency)}</dd><dt>Remaining including provisional credits</dt><dd>{money(s.remaining,s.currency)}</dd><dt>Overdue portion</dt><dd className={s.overdue>0?'overdue-amount':undefined}>{money(s.overdue,s.currency)}</dd></dl>:<p>No obligations recorded in this currency and date range. No remaining balance can be inferred.</p>}{s.ignoredCredits>0&&<p className="form-error" role="alert">{s.ignoredCredits} inconsistent credit assignment(s) excluded. Review affected obligations.</p>}</section></div><div className="treasury-movement"><div><span>Verified contributions less reported spending</span><strong>{money(s.recordedMovement,s.currency)} {s.currency}</strong></div><p>This recorded movement excludes pending and provisional contributions, opening balances, unrecorded transfers and investment values. It is not the bank balance or profit.</p></div></section>):<section className="panel empty"><h3>No group records in this range</h3><p>Record contributions, obligations or external payments to see them here.</p>{(from||to)&&<button type="button" className="secondary" onClick={reset}>Show all dates</button>}</section>}
 <section className="panel statement-section"><div className="panel-header"><h2>Contributions · {report.contributions.length}</h2></div>{report.contributions.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Payment date</TableHead><TableHead>Member / label</TableHead><TableHead>Amount</TableHead><TableHead>Current status</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{report.contributions.slice(0,limit).map(e=><TableRow key={e.id}><TableCell>{e.date}</TableCell><TableCell><strong>{org.members.find(m=>m.id===e.memberId)?.name||'Member'}</strong><small>{e.title}</small></TableCell><TableCell>{money(e.amountMinor,e.currency)} {e.currency}</TableCell><TableCell>{e.status}</TableCell><TableCell><button type="button" className="text-button" onClick={()=>onOpen(e)}>Open contribution</button></TableCell></TableRow>)}</TableBody></Table></div>:<div className="empty compact"><p>No contributions in this range.</p></div>}</section>
 <section className="panel statement-section"><div className="panel-header"><h2>External payment reports · {report.payouts.length}</h2></div>{report.payouts.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Payment date / request</TableHead><TableHead>Recipient / reference</TableHead><TableHead>Amount / fees</TableHead><TableHead>Report status</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{report.payouts.slice(0,limit).map(({request,payout:p})=><TableRow key={request.id+':'+p.id}><TableCell><strong>{p.date}</strong><small>{p.authorization.title}</small></TableCell><TableCell>{p.authorization.recipient}<small>{p.reference}</small></TableCell><TableCell>{money(p.amountMinor,p.currency)} {p.currency}<small>Fees {money(p.feeMinor,p.currency)} {p.currency}</small></TableCell><TableCell><span className="badge neutral">{p.void?'Voided report':'Owner reported'}</span><small>{p.recordedName}</small></TableCell><TableCell><button type="button" className="text-button" onClick={()=>onOpen(request)}>Open funding request</button></TableCell></TableRow>)}</TableBody></Table></div>:<div className="empty compact"><p>No external payment reports in this range.</p></div>}</section>
 <section className="panel statement-section"><div className="panel-header"><h2>Obligations · {report.dues.length}</h2></div>{report.dues.length?<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Due date</TableHead><TableHead>Member / obligation</TableHead><TableHead>Agreed amount</TableHead><TableHead>Remaining</TableHead><TableHead>Standing</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{report.dues.slice(0,limit).map(d=><TableRow key={d.entry.id}><TableCell>{d.entry.date}</TableCell><TableCell>{org.members.find(m=>m.id===d.entry.memberId)?.name||'Member'}<small>{d.entry.title}</small></TableCell><TableCell>{money(d.entry.amountMinor,d.entry.currency)} {d.entry.currency}</TableCell><TableCell>{money(d.remaining,d.entry.currency)} {d.entry.currency}</TableCell><TableCell>{d.status}</TableCell><TableCell><button type="button" className="text-button" onClick={()=>onOpen(d.entry)}>Open obligation</button></TableCell></TableRow>)}</TableBody></Table></div>:<div className="empty compact"><p>No obligations in this range.</p></div>}</section>
 {Math.max(report.contributions.length,report.payouts.length,report.dues.length)>limit&&<div className="statement-more"><p className="muted">Showing up to {limit} rows in each section. Totals and the CSV include all matching records.</p><button type="button" className="secondary" onClick={()=>setLimit(n=>n+50)}>Show more records</button></div>}</>}
 </div>;
}
