'use client';
import {useEffect,useState} from 'react';
import WorkspacePage from '../page';
import {testRoles} from '@/lib/test-workspace-options';
import type {TestContext} from '../test-workspace-controls';
export default function TestPage(){
 const [workspace,setWorkspace]=useState<{session:string;created:string}|null>(null),[context,setContext]=useState<TestContext|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[allowed,setAllowed]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/test-workspace',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Test workspace unavailable.');setAllowed(true);setWorkspace(d.workspace);const query=new URLSearchParams(window.location.search),session=query.get('session'),role=query.get('role');if(session&&d.workspace?.session===session&&testRoles.some(r=>r.id===role))setContext({session,role:role!});else if(session)setError('That test session is no longer available. Open the current workspace or create a fresh one.');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function create(){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/test-workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create'})});const d:any=await r.json();if(!r.ok||!d.workspace?.session)throw new Error(d.error||'Creation was not confirmed. Refresh before retrying.');window.location.assign(`/test?${new URLSearchParams({session:d.workspace.session,role:'admin'})}`);}catch(e){setError((e as Error).message);setBusy(false);}}
 if(context)return <WorkspacePage testContext={context}/>;
 return <main className="test-workspace-home"><section className="panel"><div className="panel-header"><div><span className="eyebrow">OWNER-ONLY TEST ENVIRONMENT</span><h1>Test workspace</h1><p>Try the full contribution and approval process with four fictional founders.</p></div></div><div className="test-home-body"><p>Test records are stored separately from your real organizations. You can switch roles without creating email accounts, leave and resume later, or delete the entire test workspace.</p><ul>{testRoles.map(r=><li key={r.id}><strong>{r.name}</strong> — {r.label}</li>)}</ul><p>There are no pre-recorded payments. The starting approval rule is two of three designated approvers. You can practice configuring weekly dues and agreements as the test administrator.</p><p>Email verification remains enabled for real accounts. This environment tests workflows and permissions, not email delivery, actual sign-in, or bank transactions.</p>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<p>Checking test workspace…</p>:allowed?<button className="primary" disabled={busy} onClick={create}>{busy?'Opening…':workspace?'Resume test workspace':'Create test workspace'}</button>:<button className="secondary" onClick={load}>Retry</button>}<a href="/" className="text-button">Return to real workspace</a></div></section></main>;
}
